$$\Large{ \textit{UNIVERSIDADE FEDERAL DO CEARÁ  } }$$

$$ \large{\textit{Departamento de Ciências da Computação }} $$


$$ \large{\textit{Mestrado e Doutorado em Ciências da Computação -  MDCC }} $$

<hr/>


$$\Large{{\textbf{ DISCIPLINA DE ÁLGEBRA LINEAR COMPUTACIONAL}}}$$

$$\large{\texttt{Docente: Professor Creto Vidal}}$$

$$\large{\texttt{Discente: Arnaldo Araújo}}$$
<hr/>



### Método de Gauss

* Definir as funções preliminares da Álgebra Linear

* Fazer o método de Gauss com pivoteamento Total e Parcial

* Método de Gauss-Jordan

    * Retorno do vetor solução 
    
    * Retorno da matriz inversa


In [2]:
#realizando os imports para todo o projeto
import numpy as np
from scipy import linalg ## testes
from pprint import pprint



In [10]:
#função para criar uma matriz NxN
def CriarMatriz(n):
    Matriz = np.mat(np.random.rand(n,n))
    return Matriz*100

In [11]:
M = []
#b = numpy.append(a,numpy.zeros([len(a),1]),1)
M = CriarMatriz(3)
M

matrix([[ 11.83283406,  84.00049102,  52.13999293],
        [ 12.06589814,  64.92761969,  30.33320803],
        [  4.59574044,  54.55152626,  44.0257932 ]])

$$ \large{\text{Um bom exemplo para testes:}} $$

In [12]:
# C = np.matrix([[1,2],[32,2]])
'''
MT2 = ([[ 61.50590283,  56.43918485,  52.9191633        ],
        [ 68.56200343,  32.71798998,  90.51044105        ],
       [ 78.41504003,  66.89005693,  94.36484943        ]])
''''


## Entrar com o vetor b tal que Ax=b

In [5]:
A = np.mat([[20.,  10.0,  0.0,0.0,0.0,0.0       ],
        [ 10.0,  20.0,  10.0,0.0,0.0,0.0        ],
            [ 0.0,10.0,  20.0,  10.0,0.0,0.0        ],
            [ 0.0,  0,  10.0,20.0,10.0,0.0        ],
            [ 0.0,0.0,0.0, 10.0,  20.0,  10.0        ],
       [0.0,0.0,0.0,0.0,10.0,20.0]])
A

matrix([[ 20.,  10.,   0.,   0.,   0.,   0.],
        [ 10.,  20.,  10.,   0.,   0.,   0.],
        [  0.,  10.,  20.,  10.,   0.,   0.],
        [  0.,   0.,  10.,  20.,  10.,   0.],
        [  0.,   0.,   0.,  10.,  20.,  10.],
        [  0.,   0.,   0.,   0.,  10.,  20.]])

In [4]:
b = np.ones((6,1),dtype = float)
b[0,0] = -10. 
b[1,0] = 10. 
b[2,0]= 20.
b[3,0] = 20.
b[4,0] = 10.
b[5,0] = -10.
b

array([[-10.],
       [ 10.],
       [ 20.],
       [ 20.],
       [ 10.],
       [-10.]])

In [7]:
MT = np.copy(A)
MT

array([[ 20.,  10.,   0.,   0.,   0.,   0.],
       [ 10.,  20.,  10.,   0.,   0.,   0.],
       [  0.,  10.,  20.,  10.,   0.,   0.],
       [  0.,   0.,  10.,  20.,  10.,   0.],
       [  0.,   0.,   0.,  10.,  20.,  10.],
       [  0.,   0.,   0.,   0.,  10.,  20.]])

## Criar a matriz estendida ( A | b)

In [8]:
MT= []
MT = np.concatenate((A,b),axis = 1)


In [9]:
MT = MT.round(2)
MT

array([[ 20.,  10.,   0.,   0.,   0.,   0., -10.],
       [ 10.,  20.,  10.,   0.,   0.,   0.,  10.],
       [  0.,  10.,  20.,  10.,   0.,   0.,  20.],
       [  0.,   0.,  10.,  20.,  10.,   0.,  20.],
       [  0.,   0.,   0.,  10.,  20.,  10.,  10.],
       [  0.,   0.,   0.,   0.,  10.,  20., -10.]])

In [10]:
# verificar se a matriz tem inversa antes de testar
# OPÇÃO - np.linalg.inv(M)

In [11]:
#função que verifica se tem inversa
def Tem_Inversa(M):
    try:
        inverse = np.linalg.inv(M)
    except np.linalg.LinAlgError:
            print("OOOPAA.....A matriz não possui inversa")
            
            pass
    else:
            print("A matriz possui inversa. Vai na fé :) ")
    # continue with what you were doing

In [12]:
Tem_Inversa(A)

A matriz possui inversa. Vai na fé :) 


In [17]:
MPP = np.copy(MT)
MPP

array([[ 20.,  10.,   0.,   0.,   0.,   0., -10.],
       [ 10.,  20.,  10.,   0.,   0.,   0.,  10.],
       [  0.,  10.,  20.,  10.,   0.,   0.,  20.],
       [  0.,   0.,  10.,  20.,  10.,   0.,  20.],
       [  0.,   0.,   0.,  10.,  20.,  10.,  10.],
       [  0.,   0.,   0.,   0.,  10.,  20., -10.]])

## PIVOTEAMENTO PARCIAL

In [15]:
#FUNÇÃO que faz o pivotemanento parcial

def Pivot_Parcial(M,j):
    aux = np.zeros(j)
    aux2 = []
    Mat = np.copy(M)
    aux = np.copy(Mat[0:,j])
    for i in range(0,j):
        aux[i] = 0
    maxindex = np.argmax(aux) #pego o maior index da coluna
    if Mat[maxindex,j]>Mat[j,j]: #se não for o maior index já está no pivô
        aux2 = np.copy(Mat[j,0:]) #copio a linha do pivô
        Mat[j,:] = Mat[maxindex,:] #mando para a linha do pivô a linha que contém o maior index
        Mat[maxindex,0:] = np.copy(aux2) #jogo na linha de maior index o pivô antigo de volta
    return Mat
            


In [18]:
MPP

array([[ 20.,  10.,   0.,   0.,   0.,   0., -10.],
       [ 10.,  20.,  10.,   0.,   0.,   0.,  10.],
       [  0.,  10.,  20.,  10.,   0.,   0.,  20.],
       [  0.,   0.,  10.,  20.,  10.,   0.,  20.],
       [  0.,   0.,   0.,  10.,  20.,  10.,  10.],
       [  0.,   0.,   0.,   0.,  10.,  20., -10.]])

In [19]:
MtGP=[]
MtGP = Pivot_Parcial(MPP,0)
MtGP

array([[ 20.,  10.,   0.,   0.,   0.,   0., -10.],
       [ 10.,  20.,  10.,   0.,   0.,   0.,  10.],
       [  0.,  10.,  20.,  10.,   0.,   0.,  20.],
       [  0.,   0.,  10.,  20.,  10.,   0.,  20.],
       [  0.,   0.,   0.,  10.,  20.,  10.,  10.],
       [  0.,   0.,   0.,   0.,  10.,  20., -10.]])

## Método de GAUSS com Pivoteamento Parcial

In [20]:
#resolver o sistema agora 
#entro com a matriz e o tamanho dela
def Gauss_Parcial(M):
    tam = M.shape[0]-1
    Ind = np.ones(M.shape[0])
    #M_I = Ind.transpose()
    Mat = np.copy(M)
    for j in range(tam):
        #faço o pivoteamento para cada coluna
        Mat = Pivot_Parcial(Mat,j)
        for i in range(tam,j,-1):
            Mat[i,:] =  Mat[i,:] - Mat[j,:] * (Mat[i,j]/Mat[j,j])
    return Mat

In [21]:
MPP

array([[ 20.,  10.,   0.,   0.,   0.,   0., -10.],
       [ 10.,  20.,  10.,   0.,   0.,   0.,  10.],
       [  0.,  10.,  20.,  10.,   0.,   0.,  20.],
       [  0.,   0.,  10.,  20.,  10.,   0.,  20.],
       [  0.,   0.,   0.,  10.,  20.,  10.,  10.],
       [  0.,   0.,   0.,   0.,  10.,  20., -10.]])

In [22]:
from IPython.core.display import display, HTML #aumentar tamanho da celular
display(HTML("<style>.container { width:100% !important; }</style>"))
MtGPP=[]
MtGPP = Gauss_Parcial(MPP)
MtGPP = MtGPP.round(2)
MtGPP


array([[ 20.  ,  10.  ,   0.  ,   0.  ,   0.  ,   0.  , -10.  ],
       [  0.  ,  15.  ,  10.  ,   0.  ,   0.  ,   0.  ,  15.  ],
       [  0.  ,   0.  ,  13.33,  10.  ,   0.  ,   0.  ,  10.  ],
       [  0.  ,   0.  ,   0.  ,  12.5 ,  10.  ,   0.  ,  12.5 ],
       [  0.  ,   0.  ,   0.  ,   0.  ,  12.  ,  10.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,  11.67, -10.  ]])

## Função de Substituição Retroativa

* Resolução do Sistema Propriamente Dito

In [23]:
MtGPP

array([[ 20.  ,  10.  ,   0.  ,   0.  ,   0.  ,   0.  , -10.  ],
       [  0.  ,  15.  ,  10.  ,   0.  ,   0.  ,   0.  ,  15.  ],
       [  0.  ,   0.  ,  13.33,  10.  ,   0.  ,   0.  ,  10.  ],
       [  0.  ,   0.  ,   0.  ,  12.5 ,  10.  ,   0.  ,  12.5 ],
       [  0.  ,   0.  ,   0.  ,   0.  ,  12.  ,  10.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,  11.67, -10.  ]])

In [24]:
A

matrix([[ 20.,  10.,   0.,   0.,   0.,   0.],
        [ 10.,  20.,  10.,   0.,   0.,   0.],
        [  0.,  10.,  20.,  10.,   0.,   0.],
        [  0.,   0.,  10.,  20.,  10.,   0.],
        [  0.,   0.,   0.,  10.,  20.,  10.],
        [  0.,   0.,   0.,   0.,  10.,  20.]])

In [44]:
#crio o vetor X de variáveis
Xv = []
for i in range(A.shape[0]):
    Xv.append('x'+str(i)) 
print(Xv)

['x0', 'x1', 'x2', 'x3', 'x4', 'x5']


In [47]:
MtGPP[5,6]

-10.0

In [48]:
## Função de substituição retroativa 
def SubsRetr(Mat1,Vx):
    #criar o vetor X
    #vx = np.copy(Vx)
    tamLi = Mat1.shape[0]
    tamCo = Mat1.shape[1]-1
    vx = np.zeros(tamLi)
    for i in range(tamLi-1,-1,-1):
        soma = 0
        for k in range(i,tamLi):
            soma =  soma + Mat1[i,k]*vx[k]
        vx[i] = (Mat1[i,tamCo] - soma)/ Mat1[i,i]
    return vx

    

In [50]:
x = []
x = SubsRetr(MtGPP,Xv)
x

array([-0.85714795,  0.7142959 ,  0.42855615,  0.42873465,  0.71408169,
       -0.85689803])

## PIVOTEAMENTO TOTAL

* ** Observações: **
    * Pivoteamento sobre colunas deve  mudar o vetor de variáveis (VETOR - X's)
    


In [52]:
#crio o vetor X de variáveis
Xv = []
for i in range(MT.shape[0]):
    Xv.append('x'+str(i)) 
print(Xv)

['x0', 'x1', 'x2', 'x3', 'x4', 'x5']


In [53]:
def Pivot_Total(M,Xv,j):
    ## ações auxiliares
    aux = np.zeros(j)
    tam_c = M.shape[1]-1
    aux2 = []
    X = np.copy(Xv)
    Mat = np.copy(M)
    aux = np.copy(Mat[:,j]) # auxiliar que verifica as linhas
    aux2 = np.copy(Mat[j,:])    #auxiliar que verifica as colunas 
    for i in range(0,j):     
        aux[i] = 0
        aux2[i] = 0
    maxindex_l = np.argmax(aux) #pego o maior index da linha
    maxindex_c = np.argmax(aux2)
    if(Mat[maxindex_l,j]>Mat[j,j]):
        if(Mat[j,maxindex_c]>Mat[maxindex_l,j]):
            aux3 = np.copy(Mat[:,j]) #copio a coluna do pivô
            Mat[:,j] = Mat[:,maxindex_c] # troco as colunas
            Mat[:,maxindex_c] = np.copy(aux3)
            #troco os valores do vetor-coluna x
            aux4 = X[j]
            X[j] = X[maxindex_c]
            X[maxindex_c] = aux4
        else:
            aux3 = np.copy(Mat[j,:]) #copio a linha  do pivô
            Mat[j,:] = Mat[maxindex_l,:] #mando para a linha do pivô a linha que contém o maior index
            Mat[maxindex_l,:] = np.copy(aux3) #jogo na linha de maior index o pivô antigo de volta
    if(Mat[j,maxindex_c]>Mat[j,j]):
        aux3 = np.copy(Mat[:,j]) #copio a coluna do pivô
        Mat[:,j] = Mat[:,maxindex_c] # troco as colunas
        Mat[:,maxindex_c] = np.copy(aux3)
        #troco os valores do vetor x
        aux4 = np.copy(X)
        aux4[j] = X[j]
        X[j] = X[maxindex_c]
        X[maxindex_c] = aux4[j]
    return Mat , X 

        
        
       


In [54]:
MT

array([[ 20.,  10.,   0.,   0.,   0.,   0., -10.],
       [ 10.,  20.,  10.,   0.,   0.,   0.,  10.],
       [  0.,  10.,  20.,  10.,   0.,   0.,  20.],
       [  0.,   0.,  10.,  20.,  10.,   0.,  20.],
       [  0.,   0.,   0.,  10.,  20.,  10.,  10.],
       [  0.,   0.,   0.,   0.,  10.,  20., -10.]])

## Método de GAUSS com Pivoteamento Total

In [66]:
#resolver o sistema agora 
#entro com a matriz 
def Gauss_Total(M,X):
    tam = M.shape[0]-1
    Mat = np.copy(M)
    for j in range(tam):
        #faço o pivoteamento total para cada coluna 
        Mat,vetx = Pivot_Total(Mat,X,j)
        for i in range(tam,j,-1):
            Mat[i,:] =  Mat[i,:] - Mat[j,:] * (Mat[i,j]/Mat[j,j])
    return Mat,vetx
   
    
        


In [67]:
MT

array([[ 20.,  10.,   0.,   0.,   0.,   0., -10.],
       [ 10.,  20.,  10.,   0.,   0.,   0.,  10.],
       [  0.,  10.,  20.,  10.,   0.,   0.,  20.],
       [  0.,   0.,  10.,  20.,  10.,   0.,  20.],
       [  0.,   0.,   0.,  10.,  20.,  10.,  10.],
       [  0.,   0.,   0.,   0.,  10.,  20., -10.]])

In [68]:
Xv

['x0', 'x1', 'x2', 'x3', 'x4', 'x5']

In [72]:
MtGPT = []
xGPT =[]
MtGPT2,xGPT2 = Gauss_Total(MT,Xv)
MtGPT2

array([[ 20.        ,  10.        ,   0.        ,   0.        ,
          0.        ,   0.        , -10.        ],
       [  0.        ,  15.        ,  10.        ,   0.        ,
          0.        ,   0.        ,  15.        ],
       [  0.        ,   0.        ,  13.33333333,  10.        ,
          0.        ,   0.        ,  10.        ],
       [  0.        ,   0.        ,   0.        ,  12.5       ,
         10.        ,   0.        ,  12.5       ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
         12.        ,  10.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,  11.66666667, -10.        ]])

$\large{\text{Para encontrar os valores finais de X iremos fazer a substituição retroativa completa.}}$

In [73]:
xGPT2

array(['x0', 'x1', 'x2', 'x3', 'x4', 'x5'],
      dtype='<U2')

In [75]:
X_sol = []
X_sol = SubsRetr(MtGPT2,xGPT2)
X_sol

array([-0.85714286,  0.71428571,  0.42857143,  0.42857143,  0.71428571,
       -0.85714286])

## Método  GAUSS_JORDAN

* M1 - Retorno: vetor solução 

* M2 - Retorno: matriz inversa

### Algoritmo
* **Entrada: A matriz b e concatenada com a matriz de entrada**
* ** Saída: A matriz identidade com o vetor-coluna b solução  **


<hr/>
$$ \large{\text{GAUSS-JORDAN RETORNANDO O VETOR SOLUÇÃO }} $$
<hr/>



In [76]:
# ESSE RETORNA UMA TRIANGULAR SUPERIOR
#resolver o sistema agora 
#entro com a matriz e o tamanho dela
def Gauss_Jordan(M,X):
    tam = M.shape[0]-1
    Ind = np.ones(M.shape[0])
    #M_I = Ind.transpose()
    Mat = np.copy(M)
    for j in range(tam):
        #faço o pivoteamento para cada coluna
        Mat,vetx = Pivot_Total(Mat,X,j)
        for i in range(tam,j,-1):
            Mat[i,:] =  Mat[i,:] - Mat[j,:] * (Mat[i,j]/Mat[j,j])
    for c in range(tam,-1,-1): #já tenho uma triangular superior. Agora vou zerar a parte de cima.
        for l in range(c-1,-1,-1):
            Mat[l,:] =  Mat[l,:] - Mat[c,:] * (Mat[l,c]/Mat[c,c])
    for p in range(tam+1):
        Mat[p,:] = Mat[p,:] * ( 1 / Mat[p,p])

    
    return Mat,vetx

In [77]:
MT

array([[ 20.,  10.,   0.,   0.,   0.,   0., -10.],
       [ 10.,  20.,  10.,   0.,   0.,   0.,  10.],
       [  0.,  10.,  20.,  10.,   0.,   0.,  20.],
       [  0.,   0.,  10.,  20.,  10.,   0.,  20.],
       [  0.,   0.,   0.,  10.,  20.,  10.,  10.],
       [  0.,   0.,   0.,   0.,  10.,  20., -10.]])

In [78]:
Xv

['x0', 'x1', 'x2', 'x3', 'x4', 'x5']

In [79]:
%%time
MtGJ = []
vetorx = []
MtGJ,vetorx = Gauss_Jordan(MT,Xv)
MtGJ

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        , -0.85714286],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.71428571],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ,  0.42857143],
       [ 0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  0.42857143],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  0.71428571],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        , -0.85714286]])

<hr/>
$$ \large{\text{RETORNANDO A MATRIZ INVERSA}} $$
<hr/>

In [80]:
A = A.round(2)
A


array([[ 20.,  10.,   0.,   0.,   0.,   0.],
       [ 10.,  20.,  10.,   0.,   0.,   0.],
       [  0.,  10.,  20.,  10.,   0.,   0.],
       [  0.,   0.,  10.,  20.,  10.,   0.],
       [  0.,   0.,   0.,  10.,  20.,  10.],
       [  0.,   0.,   0.,   0.,  10.,  20.]])

In [81]:
tamInd = A.shape[0]
I = np.identity(tamInd)
I

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

In [82]:
MTxx= []
MTxx = np.concatenate((A,I),axis = 1)
MTxx

array([[ 20.,  10.,   0.,   0.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,
          0.],
       [ 10.,  20.,  10.,   0.,   0.,   0.,   0.,   1.,   0.,   0.,   0.,
          0.],
       [  0.,  10.,  20.,  10.,   0.,   0.,   0.,   0.,   1.,   0.,   0.,
          0.],
       [  0.,   0.,  10.,  20.,  10.,   0.,   0.,   0.,   0.,   1.,   0.,
          0.],
       [  0.,   0.,   0.,  10.,  20.,  10.,   0.,   0.,   0.,   0.,   1.,
          0.],
       [  0.,   0.,   0.,   0.,  10.,  20.,   0.,   0.,   0.,   0.,   0.,
          1.]])

In [83]:
Xv

['x0', 'x1', 'x2', 'x3', 'x4', 'x5']

In [85]:
%%time
MtGJInv = []
MtGJInv = Gauss_Jordan(MTxx,Xv)
MtGJInv

(array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.08571429, -0.07142857,  0.05714286, -0.04285714,
          0.02857143, -0.01428571],
        [ 0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
          0.        , -0.07142857,  0.14285714, -0.11428571,  0.08571429,
         -0.05714286,  0.02857143],
        [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
          0.        ,  0.05714286, -0.11428571,  0.17142857, -0.12857143,
          0.08571429, -0.04285714],
        [ 0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
          0.        , -0.04285714,  0.08571429, -0.12857143,  0.17142857,
         -0.11428571,  0.05714286],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
          0.        ,  0.02857143, -0.05714286,  0.08571429, -0.11428571,
          0.14285714, -0.07142857],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
      