$$\Large{ \textit{UNIVERSIDADE FEDERAL DO CEARÁ  } }$$

$$ \large{\textit{Departamento de Ciências da Computação }} $$


$$ \large{\textit{Mestrado e Doutorado em Ciências da Computação -  MDCC }} $$

<hr/>


$$\Large{{\textbf{ DISCIPLINA DE ÁLGEBRA LINEAR COMPUTACIONAL}}}$$

$$\large{\texttt{Docente: Professor Creto Vidal}}$$

$$\large{\texttt{Discente: Arnaldo Araújo}}$$
<hr/>


# Decomposição LU

* Método visto na sala de aula.
* 
** 1- Fazer criando as duas matrizes.**
* 
** 2 - Fazer as modificações na própria matriz.**

In [1]:
#realizando os imports para todo o projeto
import numpy as np
from scipy import linalg ## testes
from __future__ import division




In [3]:
'''
#função para criar uma matriz NxN
def CriarMatriz(n):
    Matriz = np.mat(np.random.rand(n,n))
    return Matriz*100
'''


'\n#função para criar uma matriz NxN\ndef CriarMatriz(n):\n    Matriz = np.mat(np.random.rand(n,n))\n    return Matriz*100\n'

In [4]:
'''
M = []
#b = numpy.append(a,numpy.zeros([len(a),1]),1)
M = CriarMatriz(3)
'''

'\nM = []\n#b = numpy.append(a,numpy.zeros([len(a),1]),1)\nM = CriarMatriz(3)\n'

In [5]:
'''
M = M.round(2)
M
'''

'\nM = M.round(2)\nM\n'

In [2]:
A = np.mat([[20.,  10.0,  0.0,0.0,0.0,0.0       ],
        [ 10.0,  20.0,  10.0,0.0,0.0,0.0        ],
            [ 0.0,10.0,  20.0,  10.0,0.0,0.0        ],
            [ 0.0,  0,  10.0,20.0,10.0,0.0        ],
            [ 0.0,0.0,0.0, 10.0,  20.0,  10.0        ],
       [0.0,0.0,0.0,0.0,10.0,20.0]],dtype='f')


In [3]:
A

matrix([[ 20.,  10.,   0.,   0.,   0.,   0.],
        [ 10.,  20.,  10.,   0.,   0.,   0.],
        [  0.,  10.,  20.,  10.,   0.,   0.],
        [  0.,   0.,  10.,  20.,  10.,   0.],
        [  0.,   0.,   0.,  10.,  20.,  10.],
        [  0.,   0.,   0.,   0.,  10.,  20.]], dtype=float32)

In [4]:
Ateste = np.copy(A)
Ateste

array([[ 20.,  10.,   0.,   0.,   0.,   0.],
       [ 10.,  20.,  10.,   0.,   0.,   0.],
       [  0.,  10.,  20.,  10.,   0.,   0.],
       [  0.,   0.,  10.,  20.,  10.,   0.],
       [  0.,   0.,   0.,  10.,  20.,  10.],
       [  0.,   0.,   0.,   0.,  10.,  20.]], dtype=float32)

In [5]:
b = np.ones((6,1),dtype = float)
b[0,0] = -10. 
b[1,0] = 10. 
b[2,0]= 20.
b[3,0] = 20.
b[4,0] = 10.
b[5,0] = -10.
b

array([[-10.],
       [ 10.],
       [ 20.],
       [ 20.],
       [ 10.],
       [-10.]])

In [6]:
B = np.copy(b)
B

array([[-10.],
       [ 10.],
       [ 20.],
       [ 20.],
       [ 10.],
       [-10.]])

In [18]:
L = []
U = []

In [19]:
L1 = []
U1 = []
k,l,u = linalg.lu(A)
print(l)

[[ 1.          0.          0.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.          0.          0.        ]
 [ 0.          0.66666669  1.          0.          0.          0.        ]
 [ 0.          0.          0.75        1.          0.          0.        ]
 [ 0.          0.          0.          0.79999995  1.          0.        ]
 [ 0.          0.          0.          0.          0.83333337  1.        ]]


In [20]:
u

array([[ 20.        ,  10.        ,   0.        ,   0.        ,
          0.        ,   0.        ],
       [  0.        ,  15.        ,  10.        ,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,  13.33333302,  10.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,  12.5       ,
         10.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
         12.        ,  10.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,  11.66666603]], dtype=float32)

In [21]:
fator = linalg.lu_factor(A)
fator

(array([[ 20.        ,  10.        ,   0.        ,   0.        ,
           0.        ,   0.        ],
        [  0.5       ,  15.        ,  10.        ,   0.        ,
           0.        ,   0.        ],
        [  0.        ,   0.66666669,  13.33333302,  10.        ,
           0.        ,   0.        ],
        [  0.        ,   0.        ,   0.75      ,  12.5       ,
          10.        ,   0.        ],
        [  0.        ,   0.        ,   0.        ,   0.79999995,
          12.        ,  10.        ],
        [  0.        ,   0.        ,   0.        ,   0.        ,
           0.83333337,  11.66666603]], dtype=float32),
 array([0, 1, 2, 3, 4, 5], dtype=int32))

In [22]:
sol = linalg.lu_solve(fator,b)
sol

array([[-0.85714285],
       [ 0.71428569],
       [ 0.42857146],
       [ 0.42857137],
       [ 0.71428581],
       [-0.85714293]])

## Função LU 

In [46]:
def lu(A):
    n = len(A)
    L = [[0.0] * n for i in range(n)]
    U = [[0.0] * n for i in range(n)]
    for j in range(n):
        L[j][j] = 1.0
        for i in range(j+1):
            s1 = sum(U[k][j] * L[i][k] for k in range(i))
            U[i][j] = A[i][j] - s1
        for i in range(j, n):
            s2 = sum(U[k][j] * L[i][k] for k in range(j))
            L[i][j] = (A[i][j] - s2) / U[j][j]
    return (np.asanyarray(L), np.asanyarray(U))

In [47]:
Ateste

array([[ 20.,  10.,   0.,   0.,   0.,   0.],
       [ 10.,  20.,  10.,   0.,   0.,   0.],
       [  0.,  10.,  20.,  10.,   0.,   0.],
       [  0.,   0.,  10.,  20.,  10.,   0.],
       [  0.,   0.,   0.,  10.,  20.,  10.],
       [  0.,   0.,   0.,   0.,  10.,  20.]], dtype=float32)

In [48]:
%%time
L = []
U = []
L,U = lu(Ateste)


In [49]:
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.5       ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.66666667,  1.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.75      ,  1.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.8       ,  1.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.83333333,
         1.        ]])

In [50]:
U

array([[ 20.        ,  10.        ,   0.        ,   0.        ,
          0.        ,   0.        ],
       [  0.        ,  15.        ,  10.        ,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,  13.33333333,  10.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,  12.5       ,
         10.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
         12.        ,  10.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,  11.66666667]])

In [51]:
VOLTA = np.dot(L,U)
VOLTA

array([[ 20.,  10.,   0.,   0.,   0.,   0.],
       [ 10.,  20.,  10.,   0.,   0.,   0.],
       [  0.,  10.,  20.,  10.,   0.,   0.],
       [  0.,   0.,  10.,  20.,  10.,   0.],
       [  0.,   0.,   0.,  10.,  20.,  10.],
       [  0.,   0.,   0.,   0.,  10.,  20.]])

### Resolver um sistema de equações 
$$\Large{Ax = b}$$
<hr/>
$$\Large{LUx = b}$$
<hr/>
$$\large{\text{Primeiramente é encontrar y tal que:}}$$
<hr/>
$$ \Large{Ly = b} $$
<hr/>

$$\large{\text{Depois encontrar x tal que:}}$$
<hr/>
$$ \Large{Ux = y} $$

## I) Ly=b 

In [82]:
# Função de substituição retroativa 

def SubsRetrL(Mat,B):
    y = np.zeros((6,1))#criar o vetor y
    tamLi = Mat.shape[0]
    for i in range(0,tamLi):
        soma = 0
        for k in range(0,i):
            soma =  soma + Mat[i,k]*y[k]
        y[i] = (B[i] - soma)
        print(y)
        
    return y


In [83]:
B

array([[-10.],
       [ 10.],
       [ 20.],
       [ 20.],
       [ 10.],
       [-10.]])

In [84]:
vetorY2 = []
vetorY2 = SubsRetrL(L,B)
vetorY2


[[-10.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]]
[-5.]
[[-10.]
 [ 15.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]]
[ 0.]
[ 10.]
[[-10.]
 [ 15.]
 [ 10.]
 [  0.]
 [  0.]
 [  0.]]
[ 0.]
[ 0.]
[ 7.5]
[[-10. ]
 [ 15. ]
 [ 10. ]
 [ 12.5]
 [  0. ]
 [  0. ]]
[ 0.]
[ 0.]
[ 0.]
[ 10.]
[[-10. ]
 [ 15. ]
 [ 10. ]
 [ 12.5]
 [  0. ]
 [  0. ]]
[ 0.]
[ 0.]
[ 0.]
[ 0.]
[ 0.]
[[-10. ]
 [ 15. ]
 [ 10. ]
 [ 12.5]
 [  0. ]
 [-10. ]]


array([[-10. ],
       [ 15. ],
       [ 10. ],
       [ 12.5],
       [  0. ],
       [-10. ]])

## Agora encontrar o x tal que Ux = y

In [96]:
#acho que isso tá errado.
def SubsRetrU(U,y):
    x = np.zeros((6,1))#criar o vetor y
    tamLi = U.shape[0]
    for i in range(tamLi-1,-1,-1):
        soma= 0
        for k in range(i+1,tamLi):
            soma = soma + U[i,k]*x[k]
        x[i] = (y[i] - soma)/ U[i,i]
    return x
   
    

In [97]:
y

array([[-10. ],
       [ 15. ],
       [ 10. ],
       [ 12.5],
       [  0. ],
       [-10. ]])

In [98]:
U

array([[ 20.        ,  10.        ,   0.        ,   0.        ,
          0.        ,   0.        ],
       [  0.        ,  15.        ,  10.        ,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,  13.33333333,  10.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,  12.5       ,
         10.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
         12.        ,  10.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,  11.66666667]])

In [99]:
x = SubsRetrU(U,y)
x

array([[-0.85714286],
       [ 0.71428571],
       [ 0.42857143],
       [ 0.42857143],
       [ 0.71428571],
       [-0.85714286]])