$$\Large{ \textit{UNIVERSIDADE FEDERAL DO CEARÁ  } }$$

$$ \large{\textit{Departamento de Ciências da Computação }} $$


$$ \large{\textit{Mestrado e Doutorado em Ciências da Computação -  MDCC }} $$

<hr/>


$$\Large{{\textbf{ DISCIPLINA DE ÁLGEBRA LINEAR COMPUTACIONAL}}}$$

$$\large{\texttt{Docente: Professor Creto Vidal}}$$

$$\large{\texttt{Discente: Arnaldo Araújo}}$$
<hr/>


# Decomposição Cholesky 

## Passos - Necessidades
* *** Precisa ser simétrica ***

* ***  Matriz Positiva  *** 

* $ \text{Basicamente é decompor de modo que: } \mathbf{A} = \mathbf{S} \mathbf{S}^\top$

In [1]:
#realizando os imports para todo o projeto
import numpy as np
from scipy import linalg ## testes
from __future__ import print_function 
from pprint import pprint
from math import sqrt


In [2]:
#funçao para criar uma matriz simétrica
def Simetrica(n):
    Matriz = np.mat(np.random.rand(n,n))
    symm = Matriz*100
    symm = (symm + symm.T)/2
    return symm.round(2)

### Verificar se é Positiva Definida


In [3]:
def isPSD(A, tol=1e-8):
    E,V = scipy.linalg.eigh(A)
    return np.all(E > -tol)

## Função Decomposicão Cholesky 

In [6]:
def choleskyakdsgjasijasdgarokaanj(A):
    L = [[0.0] * len(A) for _ in range(len(A))]
    for i in range(len(A)):
        for j in range(i+1):
            s = sum(L[i][k] * L[j][k] for k in range(j))
            L[i][j] = sqrt(A[i][i] - s) if (i == j) else \
                      ((1.0 / L[j][j]) * (A[i][j] - s))
    return np.asanyarray(L)

### Matrizes para teste 

In [2]:
A = np.mat([[20.,  10.0,  0.0,0.0,0.0,0.0       ],
        [ 10.0,  20.0,  10.0,0.0,0.0,0.0        ],
            [ 0.0,10.0,  20.0,  10.0,0.0,0.0        ],
            [ 0.0,  0,  10.0,20.0,10.0,0.0        ],
            [ 0.0,0.0,0.0, 10.0,  20.0,  10.0        ],
       [0.0,0.0,0.0,0.0,10.0,20.0]],dtype='f')
A

matrix([[ 20.,  10.,   0.,   0.,   0.,   0.],
        [ 10.,  20.,  10.,   0.,   0.,   0.],
        [  0.,  10.,  20.,  10.,   0.,   0.],
        [  0.,   0.,  10.,  20.,  10.,   0.],
        [  0.,   0.,   0.,  10.,  20.,  10.],
        [  0.,   0.,   0.,   0.,  10.,  20.]], dtype=float32)

In [3]:
Ateste = np.copy(A)
Ateste

array([[ 20.,  10.,   0.,   0.,   0.,   0.],
       [ 10.,  20.,  10.,   0.,   0.,   0.],
       [  0.,  10.,  20.,  10.,   0.,   0.],
       [  0.,   0.,  10.,  20.,  10.,   0.],
       [  0.,   0.,   0.,  10.,  20.,  10.],
       [  0.,   0.,   0.,   0.,  10.,  20.]], dtype=float32)

In [4]:
b = np.ones((6,1),dtype = float)
b[0,0] = -10. 
b[1,0] = 10. 
b[2,0]= 20.
b[3,0] = 20.
b[4,0] = 10.
b[5,0] = -10.
b

array([[-10.],
       [ 10.],
       [ 20.],
       [ 20.],
       [ 10.],
       [-10.]])

In [7]:
%%time
S = choleskyakdsgjasijasdgarokaanj(Ateste)
S

array([[ 4.47213595,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 2.23606798,  3.87298335,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  2.5819889 ,  3.65148372,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  2.73861279,  3.53553391,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  2.82842712,  3.46410162,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  2.88675135,
         3.41565026]])

### Achar a transposta 

In [9]:
#TRANSPOR A MATRIZ 
ST = np.transpose(S)
ST

array([[ 4.47213595,  2.23606798,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  3.87298335,  2.5819889 ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  3.65148372,  2.73861279,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  3.53553391,  2.82842712,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  3.46410162,
         2.88675135],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         3.41565026]])

### Verificar se a decomposição foi bem feita

In [11]:
#VERIFICAR SE A DECOMPOSIÇÃO FOI BEM FEITA
VOLTASST = np.dot(S,ST)
VOLTASST

array([[ 20.,  10.,   0.,   0.,   0.,   0.],
       [ 10.,  20.,  10.,   0.,   0.,   0.],
       [  0.,  10.,  20.,  10.,   0.,   0.],
       [  0.,   0.,  10.,  20.,  10.,   0.],
       [  0.,   0.,   0.,  10.,  20.,  10.],
       [  0.,   0.,   0.,   0.,  10.,  20.]])

<h\>
********************************************************
<h\>
********************************************************
<h\>

## Resolvendo sistemas lineares com o Cholesky

* passo somente a matriz e o vetor B e ele me retorna a Soluçao

In [15]:
b = np.ones((6,1),dtype = float)
b[0,0] = -10. 
b[1,0] = 10. 
b[2,0]= 20.
b[3,0] = 20.
b[4,0] = 10.
b[5,0] = -10.
b

array([[-10.],
       [ 10.],
       [ 20.],
       [ 20.],
       [ 10.],
       [-10.]])

In [19]:
B = np.copy(b)
B

array([[-10.],
       [ 10.],
       [ 20.],
       [ 20.],
       [ 10.],
       [-10.]])

### Resolver um sistema de equações 
$$\Large{Ax = b}$$
<hr/>
$$\Large{SS^{T}x=b}$$
<hr/>
$$\large{\text{Primeiramente é encontrar y tal que:}}$$
<hr/>
$$ \Large{Sy = b} $$
<hr/>

$$\large{\text{Depois encontrar x tal que:}}$$
<hr/>
$$ \Large{S^{T}x = y} $$

In [12]:
S[:,0]

array([ 4.47213595,  2.23606798,  0.        ,  0.        ,  0.        ,  0.        ])

In [14]:
S[0,:]# S é como se fosse uma L

array([ 4.47213595,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ])

In [22]:
# Função de substituição retroativa para uma triangular inferior 

def SubsRetrL(Mat,B):
    y = np.zeros((6,1))#criar o vetor y
    tamLi = Mat.shape[0]
    for i in range(0,tamLi):
        soma = 0
        for k in range(0,i):
            soma =  soma + Mat[i,k]*y[k]
        y[i] = (B[i] - soma)/Mat[i,i]
        
    return y


In [24]:
S

array([[ 4.47213595,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 2.23606798,  3.87298335,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  2.5819889 ,  3.65148372,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  2.73861279,  3.53553391,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  2.82842712,  3.46410162,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  2.88675135,
         3.41565026]])

In [25]:
B

array([[-10.],
       [ 10.],
       [ 20.],
       [ 20.],
       [ 10.],
       [-10.]])

In [26]:
vetorY = []
vetorY = SubsRetrL(S,B)
vetorY

array([[ -2.23606798e+00],
       [  3.87298335e+00],
       [  2.73861279e+00],
       [  3.53553391e+00],
       [  1.53837015e-15],
       [ -2.92770022e+00]])

In [27]:
# agora St * x = y
def SubsRetrU(U,y):
    x = np.zeros((6,1))#criar o vetor y
    tamLi = U.shape[0]
    for i in range(tamLi-1,-1,-1):
        soma= 0
        for k in range(i+1,tamLi):
            soma = soma + U[i,k]*x[k]
        x[i] = (y[i] - soma)/ U[i,i]
    return x


In [28]:
vetorX = []
vetorX = SubsRetrU(ST,vetorY)
vetorX

array([[-0.85714286],
       [ 0.71428571],
       [ 0.42857143],
       [ 0.42857143],
       [ 0.71428571],
       [-0.85714286]])