$$\Large{ \textit{UNIVERSIDADE FEDERAL DO CEARÁ  } }$$

$$ \large{\textit{Departamento de Ciências da Computação }} $$


$$ \large{\textit{Mestrado e Doutorado em Ciências da Computação -  MDCC }} $$

<hr/>


$$\Large{{\textbf{ DISCIPLINA DE ÁLGEBRA LINEAR COMPUTACIONAL}}}$$



$$\large{\texttt{Docente: Professor Creto Vidal}}$$

$$\large{\texttt{Discente: Arnaldo Araújo}}$$
<hr/>


# DECOMPOSIÇÃO QR ( HOUSEHOLDER )

<hr/>

$$\Large{\text{Dado: } A_{nxm} \rightarrow  R = A_{n-1} = H_{n-1} H_{n-2} \ldots H_{2} H_{1} A \\
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \\
\text{HOUSEHOLDER:  }  H_{mxm}  = I_{mxm} - 2nn^{T} }$$
<hr/>
$$\Large{QR = QQ^{T}A \therefore QR = A}$$
<hr/>
$$\large{\text{A essência do método é encontrar R tal que:}}$$
<hr/>
$$ \Large{QA = R} $$
<hr/>

$$\large{\text{ONDE: } Q \text{ será encontrada pelas operações sobres os H's encontrados} }$$
<hr/>


In [1]:
#realizando os imports para todo o projeto
import numpy as np
from scipy import linalg as LA ## testes
from __future__ import print_function 
from pprint import pprint
from math import sqrt
from scipy import random, linalg, dot, diag, all, allclose
from __future__ import print_function 
from pprint import pprint


In [2]:
#Matriz para os testes Iniciais
A = np.array([[12.0,-51.0,4],[6.0,167.0,-68.0],[-4.0,24.0,-41.0]])
A

array([[  12.,  -51.,    4.],
       [   6.,  167.,  -68.],
       [  -4.,   24.,  -41.]])

In [2]:
import numpy as np
 
def QR_HH(A):
    m, n = A.shape
    Q = np.eye(m,n)
    for i in range(n - (m == n)): #preciso operacionar sobre as colunas da matriz "A"
        H = np.eye(m)
        H[i:, i:] = Householder(A[i:, i])
        print("matriz HouseHolder",H)
        Q = np.dot(Q, H)
        print("matriz Q",Q)
        A = np.dot(H, A)
        print("matriz A",A.round(2))
    return Q, A
 
def Householder(a):
    v = a / (a[0] + np.copysign(np.linalg.norm(a), a[0]))
    v[0] = 1
    H = np.eye(a.shape[0])
    H -= (2 / np.dot(v, v)) * np.dot(v[:, None], v[None, :])
    return H
 

In [151]:
A

array([[  12.,  -51.,    4.],
       [   6.,  167.,  -68.],
       [  -4.,   24.,  -41.]])

In [152]:
Q1,A1 = qr(A)


matriz HouseHolder [[-0.85714286 -0.42857143  0.28571429]
 [-0.42857143  0.9010989   0.06593407]
 [ 0.28571429  0.06593407  0.95604396]]
matriz Q [[-0.85714286 -0.42857143  0.28571429]
 [-0.42857143  0.9010989   0.06593407]
 [ 0.28571429  0.06593407  0.95604396]]
matriz A [[ -14.    -21.     14.  ]
 [  -0.    173.92  -65.69]
 [   0.     19.38  -42.54]]
matriz HouseHolder [[ 1.          0.          0.        ]
 [ 0.         -0.99384615 -0.11076923]
 [ 0.         -0.11076923  0.99384615]]
matriz Q [[-0.85714286  0.39428571  0.33142857]
 [-0.42857143 -0.90285714 -0.03428571]
 [ 0.28571429 -0.17142857  0.94285714]]
matriz A [[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]


In [105]:
Q1,A1 = qr(A) #A1 é a matriz R
AVolta = np.dot(Q1,A1)
A1.round(2)

[ 0.46153846  0.23076923 -0.15384615]
[ 0.49845679  0.05555556]


array([[ -14.,  -21.,   14.],
       [   0., -175.,   70.],
       [   0.,    0.,  -35.]])

In [103]:
AVolta

array([[  12.,  -51.,    4.],
       [   6.,  167.,  -68.],
       [  -4.,   24.,  -41.]])

In [37]:
A

array([[  12.,  -51.,    4.],
       [   6.,  167.,  -68.],
       [  -4.,   24.,  -41.]])

$$ \large\text{ DECOMPOSIÇÃO QR por JACOBI( MATRIZES DE ROTAÇÃO DE GIVENS ) }$$
<hr/>


In [3]:
A = np.array([[12.0,-51.0,4],[6.0,167.0,-68.0],[-4.0,24.0,-41.0]])
A

array([[  12.,  -51.,    4.],
       [   6.,  167.,  -68.],
       [  -4.,   24.,  -41.]])

In [5]:
m,n = A.shape
H = np.eye(m)
H

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [143]:
A

array([[  12.,  -51.,    4.],
       [   6.,  167.,  -68.],
       [  -4.,   24.,  -41.]])

In [6]:
m,n=A.shape
n

3

In [8]:
J

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [9]:
m = A.shape[0]
m

3

In [121]:
def jacobi_qr(A): #matrizes de rotação de Givens
    l,c = A.shape
    Q = np.eye(l,c)
    R = np.copy(A)
    for j in range(0,c):
        for i in range(j+1,l):
            J = np.eye(l)
            theta = np.arctan(A[i,j]/A[j,j])
            J[j,j] = np.cos(theta)
            J[i,j] = -(np.sin(theta))
            J[j,i] = np.sin(theta)
            J[i,i] = np.cos(theta)
            R = np.dot(J,R)
            Q = np.dot(Q,J.T)
    return (Q,R)



In [134]:
A

array([[  12.,  -51.,    4.],
       [   6.,  167.,  -68.],
       [  -4.,   24.,  -41.]])

In [130]:
Qteste = []
Rteste = []
Qteste,Rteste =  jacobi_qr(A)

In [131]:
Qteste

array([[ 0.84852814, -0.40243101,  0.343583  ],
       [ 0.42426407,  0.90544875,  0.01274993],
       [-0.31622777,  0.13495125,  0.93903576]])

In [133]:
np.dot(Qteste,Rteste)

array([[  12.,  -51.,    4.],
       [   6.,  167.,  -68.],
       [  -4.,   24.,  -41.]])

In [6]:
A = np.array([[12.0,-51.0,4],[6.0,167.0,-68.0],[-4.0,24.0,-41.0]])
G= np.eye(3)
theta = np.arctan((-A[2,0])/A[0,0])
G[0,0] = np.cos(theta)
G[m-1,0] = np.sin(theta)
G[0,n-1] = -(np.sin(theta))
G[m-1,n-1] = np.cos(theta)
TesteJACOB = np.dot(G,A)
TesteJACOB

array([[  12.64911064,  -55.97231458,   16.7600716 ],
       [   6.        ,  167.        ,  -68.        ],
       [   0.        ,    6.64078309,  -37.63110416]])

In [35]:
A

array([[  12.,  -51.,    4.],
       [   6.,  167.,  -68.],
       [  -4.,   24.,  -41.]])

In [10]:
A_2 = np.copy(TesteJACOB)
A_2

array([[  12.64911064,  -55.97231458,   16.7600716 ],
       [   6.        ,  167.        ,  -68.        ],
       [   0.        ,    6.64078309,  -37.63110416]])

In [7]:
G

array([[ 0.9486833 ,  0.        , -0.31622777],
       [ 0.        ,  1.        ,  0.        ],
       [ 0.31622777,  0.        ,  0.9486833 ]])

In [11]:
G_2= np.eye(3)
theta = np.arctan((-A_2[1,0])/A_2[0,0])
G_2[0,0] = np.cos(theta)
G_2[m-1,0] = np.sin(theta)
G_2[0,n-1] = -(np.sin(theta))
G_2[m-1,n-1] = np.cos(theta)
G_2

array([[ 0.9035079 ,  0.        ,  0.42857143],
       [ 0.        ,  1.        ,  0.        ],
       [-0.42857143,  0.        ,  0.9035079 ]])

<hr/>

$$\Large{\text{Decomposição QR por Gram-Schimit}}$$

<hr/>


In [3]:
A

array([[  12.,  -51.,    4.],
       [   6.,  167.,  -68.],
       [  -4.,   24.,  -41.]])

In [15]:
l,c = A.shape
Q = np.zeros((l,c))
x = A[:,0]
e = x/(LA.norm(x))
Q[:,0] = np.copy(e)
Q

array([[ 0.85714286,  0.        ,  0.        ],
       [ 0.42857143,  0.        ,  0.        ],
       [-0.28571429,  0.        ,  0.        ]])

In [31]:
x = A[:,1]
x = x - (np.dot(np.dot(x,Q[:,0]),Q[:,0]))
e = x/(LA.norm(x))
Q[:,1] = np.copy(e)
Q


array([[ 0.85714286, -0.39428571,  0.        ],
       [ 0.42857143,  0.90285714,  0.        ],
       [-0.28571429,  0.17142857,  0.        ]])

In [32]:
A[:,0]

array([ 12.,   6.,  -4.])

In [50]:
for p in range(1,0,-1):
    print(p-1)

0


In [ ]:
#para k =1


In [66]:
def GramShimit(A):
    l,c = A.shape
    Q = np.zeros((l,c))
    x = A[:,0]
    e = x/(LA.norm(x))
    Q[:,0] = np.copy(e)
    for i in range(1,c):
        s = 0
        for k in range(i,0,-1):
            s = s + np.dot(np.dot(A[:,i],Q[:,k-1]),Q[:,k-1])
        x = A[:,i] - s
        e = x/(LA.norm(x))
        Q[:,i] = np.copy(e)
        R = np.dot(Q.T,A)
    
    return (Q,R)
        

    

In [67]:
Q1,R1 = GramShimit(A)


In [68]:
Q1

array([[ 0.85714286, -0.39428571, -0.33142857],
       [ 0.42857143,  0.90285714,  0.03428571],
       [-0.28571429,  0.17142857, -0.94285714]])

In [70]:
R1.round(2)

array([[  14.,   21.,  -14.],
       [  -0.,  175.,  -70.],
       [  -0.,   -0.,   35.]])

In [60]:
QTeste.T

array([[ 0.85714286,  0.42857143, -0.28571429],
       [-0.39428571,  0.90285714,  0.17142857],
       [-0.33142857,  0.03428571, -0.94285714]])

In [63]:
RTeste = np.dot(QTeste.T,A)
RTeste.round(2)

array([[  14.,   21.,  -14.],
       [  -0.,  175.,  -70.],
       [  -0.,   -0.,   35.]])

In [37]:
sum( P[:,k] for k in range(3,0))

0

In [ ]:
def gs(X, row_vecs=True, norm = True):
    if not row_vecs:
        X = X.T
    Y = X[0:1,:].copy()
    for i in range(1, X.shape[0]):
        proj = np.diag((X[i,:].dot(Y.T)/np.linalg.norm(Y,axis=1)**2).flat).dot(Y)
        Y = np.vstack((Y, X[i,:] - proj.sum(0)))
    if norm:
        Y = np.diag(1/np.linalg.norm(Y,axis=1)).dot(Y)
    if row_vecs:
        return Y
    else:
        return Y.T

$$\Large{\text{RESOLVENDO SISTEMAS DE EQUAÇÕES POR QR}}$$

$$\Large{Ax = b}$$
<hr/>
$$\Large{A = QR \therefore QRx = b}$$
<hr/>
$$\large{\text{Multiplicando pela transposta de Q nos dois lados temos que:}}$$
<hr/>
$$ \Large{ Q^{T}QRx = Q^{T}b \therefore Rx = Q^{T}b} $$
<hr/>

$$\large{\text{Desenvolvendo o lado esquerdo da equação temos finalmente que :}}$$
<hr/>
$$ \Large{Rx = \tilde{b},onde \ \  \tilde{b}=Q^{T}b } $$

In [99]:
#Retrosubstituição para encontrar o x 
def SubsRetrR(R,b):
    l,c = R.shape
    x = np.zeros((l,1))#criar o vetor y
    for i in range(l-1,-1,-1):
        soma= 0
        for k in range(i+1,l):
            soma = soma + R[i,k]*x[k]
        x[i] = (b[i][0] - soma)/ R[i,i]
    return x


In [112]:
def solverQR(A,b): # o vetor b deve ser um vetor coluna b_nx1
    l,c = A.shape
    x = np.zeros((l,1))
    Q,R = GramShimit(A)
    bMod = np.dot(Q.T,b.T)
    x= SubsRetrR(R,bMod)
    return(x)
    
        
        

In [113]:
b = np.array([[2.0,1.0,5.0]])
b.T.shape

(3, 1)

In [114]:
A

array([[  12.,  -51.,    4.],
       [   6.,  167.,  -68.],
       [  -4.,   24.,  -41.]])

In [115]:
Q_1,R_1 = GramShimit(A)
Q_1

array([[ 0.85714286, -0.39428571, -0.33142857],
       [ 0.42857143,  0.90285714,  0.03428571],
       [-0.28571429,  0.17142857, -0.94285714]])

In [116]:
R_1.round(2)

array([[  14.,   21.,  -14.],
       [  -0.,  175.,  -70.],
       [  -0.,   -0.,   35.]])

In [117]:
x = solverQR(A,b)
x

array([[-0.01836735],
       [-0.0555102 ],
       [-0.15265306]])