$$\Large{ \textit{UNIVERSIDADE FEDERAL DO CEARÁ  } }$$

$$ \large{\textit{Departamento de Ciências da Computação }} $$


$$ \large{\textit{Mestrado e Doutorado em Ciências da Computação -  MDCC }} $$

<hr/>

$$\Large{{\textbf{ DISCIPLINA DE ÁLGEBRA LINEAR COMPUTACIONAL}}}$$



$$\large{\texttt{Docente: Professor Creto Vidal}}$$

$$\large{\texttt{Discente: Arnaldo Araújo}}$$
<hr/>


# MÉTODO DA POTÊNCIA

In [1]:
#realizando os imports para todo o projeto
import numpy as np
from scipy import linalg as LA ## testes
from __future__ import print_function 
from pprint import pprint
from math import sqrt
from scipy import random, linalg, dot, diag, all, allclose
from __future__ import print_function 
from pprint import pprint


In [4]:
#Matriz para os testes Iniciais
A = np.array([[12.0,-51.0,4],[6.0,167.0,-68.0],[-4.0,24.0,-41.0]])
A

array([[  12.,  -51.,    4.],
       [   6.,  167.,  -68.],
       [  -4.,   24.,  -41.]])

In [3]:
#matriz do rodolfo
MRod = np.array([[4.0, 0.,   0.,   0.],
   [0. ,  2.,   4.,   0],
   [0.,   0.,   2.,   0.],
   [0.,   0.,   0.,   2.]])
MRod

array([[ 4.,  0.,  0.,  0.],
       [ 0.,  2.,  4.,  0.],
       [ 0.,  0.,  2.,  0.],
       [ 0.,  0.,  0.,  2.]])

In [80]:
tol = 1.0e-6
fator = abs((Av2-Av3)/Av3)
if(tol>fator):
    print("continua")
else:
    print("fator é maior")

fator é maior


In [81]:
k = 0
while k<5:
    k = k+1
print(k)
    

5


In [4]:
#AUTOVALORES E AUTOVETORES PELO MÉTODO DA POTÊNCIA
def AA_mpot(A):   
    l,c = A.shape
    v = np.random.rand(l,1)
    q_zero = v/ LA.norm(v)
    y_zero = np.dot(A,q_zero)
    Av_zero = np.dot(q_zero.T,y_zero)
    #y = np.copy(y_zero)
    k = 0
    while(k<100):
        q = y_zero /LA.norm(y_zero)
        y = np.dot(A,q)
        Av = np.dot(q.T,y)
        #analiso a AV e o AV_zero
        k = k+1
        y_zero = np.copy(y) #autovetor
        Av_zero = np.copy(Av) #autovalor
    return (Av,y)
    

In [86]:
AA_mpot(A)

(array([[ 6.]]), array([[ 4.78440288],
        [ 3.41743063],
        [-1.19610072]]))

In [5]:
AA_mpot(MRod)

(array([[ 4.]]), array([[  4.00000000e+00],
        [  3.62771003e-28],
        [  1.79454254e-30],
        [  6.57050098e-31]]))

# MÉTODO DA POTÊNCIA INVERSA 

In [16]:
A =  np.array([[2.0,1.0,0.0],[2.,5.,3.],[0.0,1.,6.]])
A

array([[ 2.,  1.,  0.],
       [ 2.,  5.,  3.],
       [ 0.,  1.,  6.]])

In [6]:
MRod

array([[ 4.,  0.,  0.,  0.],
       [ 0.,  2.,  4.,  0.],
       [ 0.,  0.,  2.,  0.],
       [ 0.,  0.,  0.,  2.]])

In [7]:
#AUTOVALORES E AUTOVETORES PELO MÉTODO DA POTÊNCIA INVERSA
def AAInv_mpot(A):   
    l,c = A.shape
    v = np.random.rand(l,1)
    q_zero = v/ LA.norm(v)
    #A = LU 
    LU = linalg.lu_factor(A)
    y_zero = linalg.lu_solve(LU, q_zero) 
    Av_zero = np.dot(q_zero.T,y_zero)
    AvInv_zero = 1/(Av_zero)
    k = 0
    while(k<100):
        q = y_zero /LA.norm(y_zero)
        y = linalg.lu_solve(LU,q)
        AvInv = np.dot(q.T,y)
        #analiso a AV e o AV_zero
        k = k+1
        y_zero = np.copy(y) #autovetor
        AvInv = 1/(AvInv)
        AvInv_zero = np.copy(AvInv) #autovalor
    return (AvInv,y)


In [26]:
AAInv_mpot(A)

(array([[ 1.3375352]]), array([[ 0.61895637],
        [-0.41003681],
        [ 0.08794422]]))

In [8]:
AAInv_mpot(MRod)

(array([[ 1.98006905]]), array([[  5.90328951e-33],
        [ -5.04728124e-01],
        [  2.51799614e-03],
        [  1.73618174e-02]]))

## Autovalores, ESTIMATIVAS A PRIORI

## Teorema de Gerschgorin

In [2]:
#Teorema de Gerschgorin
# testes
A = np.array([[10.0,-1.0,0.,1],[0.2,8.0,0.2,0.2],[1.,1.,2.,1.],[-1.,-1.,-1.,-11.,]])
A

array([[ 10. ,  -1. ,   0. ,   1. ],
       [  0.2,   8. ,   0.2,   0.2],
       [  1. ,   1. ,   2. ,   1. ],
       [ -1. ,  -1. ,  -1. , -11. ]])

In [19]:
def Gerschgorin(A):
    l,c = A.shape
    x = sum(np.abs(A[0][:])) - np.abs(A[0][0])
    piso_zero = A[0][0] - x
    teto_zero = A[0][0] + x
    for i in range(1,l):
        x = sum(np.abs(A[i][:])) - np.abs(A[i][i])
        piso = A[i][i] - x
        teto = A[i][i] + x
        if teto>teto_zero:
            teto_zero = teto
        if piso<piso_zero:
            piso_zero = piso
    return(piso_zero,teto_zero)
        
        
    

In [10]:
Gerschgorin(A)

(-14.0, 12.0)

In [14]:
mi = random.uniform(piso_zero, teto_zero)
mi

1.6435793515917752

In [15]:
A =  np.array([[2.0,1.0,0.0],[2.,5.,3.],[0.0,1.,6.]])
A

array([[ 2.,  1.,  0.],
       [ 2.,  5.,  3.],
       [ 0.,  1.,  6.]])

In [30]:
# ESTIMATIVA DE UM AUTOVALOR entre o Autovalor Máximo e o Autovalor Mínimo
def AAEstim(A):
    piso,teto = Gerschgorin(A)
    mi = random.uniform(piso, teto)
    l,c = A.shape
    I = np.identity(l)
    I = I*mi
    Abarra = A - I
    Avmi,yEst = AAInv_mpot(Abarra)
    AvEst = Avmi + mi 
    return(AvEst,yEst)

array([[-0.25934491]])

In [31]:
AvEst = Avmi + mi 
AvEst

array([[ 7.44437482]])

In [2]:
#A deve ser simétrica
A =  np.array([[1.,  2.,  6.,  8.], 
[2.,  5.,  7.,  -3.],
[6.,  7.,  9.,  4.],
[8.,  -3., 4.,  3.]])
A

array([[ 1.,  2.,  6.,  8.],
       [ 2.,  5.,  7., -3.],
       [ 6.,  7.,  9.,  4.],
       [ 8., -3.,  4.,  3.]])

In [4]:
Q,R = np.linalg.qr(A)

In [5]:
Q

array([[-0.09759001, -0.19357357,  0.86349608, -0.45538992],
       [-0.19518001, -0.50006505,  0.28469563,  0.7942217 ],
       [-0.58554004, -0.59685183, -0.39868141, -0.37678094],
       [-0.78072006,  0.59685183,  0.11990014,  0.14095402]])

In [6]:
R

array([[-10.24695077,  -2.92770022, -10.34454077,  -4.87950036],
       [  0.        ,  -8.85599071,  -7.64615591,  -0.64524522],
       [  0.        ,   0.        ,   4.06531376,   4.81885657],
       [  0.        ,   0.        ,   0.        ,  -7.11004614]])

In [7]:
np.dot(R,Q)

array([[ 11.43809524,   6.70939875,  -6.14258198,   5.55095564],
       [  6.70939875,   8.6070778 ,   0.44975341,  -4.24364407],
       [ -6.14258198,   0.44975341,  -1.04298344,  -0.85249554],
       [  5.55095564,  -4.24364407,  -0.85249554,  -1.0021896 ]])

In [8]:
np.dot(np.dot(Q.T,A),Q)

array([[ 11.43809524,   6.70939875,  -6.14258198,   5.55095564],
       [  6.70939875,   8.6070778 ,   0.44975341,  -4.24364407],
       [ -6.14258198,   0.44975341,  -1.04298344,  -0.85249554],
       [  5.55095564,  -4.24364407,  -0.85249554,  -1.0021896 ]])

$$\Large\text{TRIDIAGONALIZAÇÃO DE MATRIZES SIMÉTRICAS POR HOUSEHOLDER}$$

In [3]:
#A deve ser simétrica
Asimetrica =  np.array([[1.,  2.,  6.,  8.], 
[2.,  5.,  7.,  -3.],
[6.,  7.,  9.,  4.],
[8.,  -3., 4.,  3.]])
Asimetrica

array([[ 1.,  2.,  6.,  8.],
       [ 2.,  5.,  7., -3.],
       [ 6.,  7.,  9.,  4.],
       [ 8., -3.,  4.,  3.]])

In [21]:
l,c = A.shape
c

4

In [24]:
np.linalg.norm(A[0:4,0])

10.246950765959598

In [26]:
np.sqrt(np.dot(A[0:4,0],A[0:4,0]))

10.246950765959598

In [28]:
v = A[0+1:,0]
v

array([ 2.,  6.,  8.])

In [29]:
u = np.linalg.norm(v)
u

10.198039027185569

In [ ]:
if v[0] < 0.0: 
    u = -u # se o primeiro valor for negativo eu mudo o valor da norma


In [30]:
v[0] = v[0]+u
v

array([ 12.19803903,   6.        ,   8.        ])

In [31]:
h = np.dot(v,v)/2.0
h

124.39607805437113

In [34]:
A

array([[  1.        ,   2.        ,   6.        ,   8.        ],
       [ 12.19803903,   5.        ,   7.        ,  -3.        ],
       [  6.        ,   7.        ,   9.        ,   4.        ],
       [  8.        ,  -3.        ,   4.        ,   3.        ]])

In [33]:
A[0+1:,0+1:]

array([[ 5.,  7., -3.],
       [ 7.,  9.,  4.],
       [-3.,  4.,  3.]])

In [35]:
Vt = np.dot(A[0+1:,0+1:],v)/h
Vt

array([ 0.63498943,  1.3777466 ,  0.09169005])

In [37]:
g = np.dot(v,Vt)/(2.0*h)
g

0.067307692307692318

In [38]:
Vt = Vt - g*u
Vt

array([-0.05141704,  0.69134012, -0.59471642])

In [45]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [47]:
u = np.array([5.74,3,-1])
np.dot(u,u.T)

42.947600000000001

In [48]:
u

array([ 5.74,  3.  , -1.  ])

In [6]:
def HH_HENS(A):
    l,c = A.shape
    for i in range(l-2):
        u = A[i+1:,i]
        k = np.linalg.norm(u)
        if u[0]<0.0:
            k = -k  #  PQ DISSO mesmo?
        u[0] = u[0] + k
        h = np.dot(u,u)/2.0 # 1/2 da norma ao quadrado de u 
        v = np.dot(A[i+1:,i+1:],u)/h
        g = np.dot(u,v)/(2*h)
        v = v - g*u
        A[i+1:,i+1:] = A[i+1:,i+1:] - np.outer(v,u)
        A[i,i+1]= -k
    return A
        
        
    
    

In [8]:
HH_HENS(Asimetrica)

array([[  1.        , -10.19803903,   6.        ,   8.        ],
       [ 12.19803903,   7.26923077,   5.46007698,  -1.51174061],
       [  6.        , -10.33975259,   0.57212318,  -3.17887947],
       [  8.        ,   2.44973602,  -4.22782128,   9.15864605]])

In [ ]:
def testeHHHH(Mat):
    A = np.copy(Mat)
    l,c = A.shape
    for i in range(l-2):
        x = A[i+1:,i]
        k = np.linalg.norm(x)
        u= np.copy(x)
        if u[0]<0.0:
            k = -k  # PERGUNTAR AO PROFESSOR PQ DISSO
        u[0] = u[0] + k
    
    
    
    

In [136]:
def TriD_HH(Mat): 
    A = np.copy(Mat)
    l,c = A.shape
    for i in range(l-2):
        x = A[i+1:,i]
        k = np.linalg.norm(x)
        u= np.copy(x)
        if u[0]<0.0:
            k = -k  # PERGUNTAR AO PROFESSOR PQ DISSO
        u[0] = u[0] + k
        h = np.dot(u,u)/2.0 # 1/2 da norma ao quadrado de u 
        Matu = np.outer(u,u)
        n  = len(Matu)
        Q = np.eye(n)
        Q = Q - (Matu/h)
        A_HH = np.eye((n))
        A_HH = A[i+1:,i+1:]
        A_HH = np.dot(np.dot(Q,A_HH),Q)
        Qx = np.dot(Q,x)
        Qx[0] = -k
        A[i,i+1:] = Qx.T
        A[i+1:,i] = Qx
        A[i+1:,i+1:] = A_HH
    return A.round(4)


In [137]:
Asimetrica

array([[ 1.,  2.,  6.,  8.],
       [ 2.,  5.,  7., -3.],
       [ 6.,  7.,  9.,  4.],
       [ 8., -3.,  4.,  3.]])

In [129]:
TriD = TriD_HH(Asimetrica)
TriD

array([[  1.    , -10.198 ,   0.    ,   0.    ],
       [-10.198 ,   9.5385,   5.4472,   0.    ],
       [  0.    ,   5.4472,   5.1309,   6.3607],
       [  0.    ,   0.    ,   6.3607,   2.3306]])

$$\Large\text{DIAGONALIZAÇÃO DE UMA MATRIZ TRIDIAGONAL POR QR}$$

In [130]:
#SEJA A SEGUINTE MATRIZ TRIDIAGONAL 
TriD

array([[  1.    , -10.198 ,   0.    ,   0.    ],
       [-10.198 ,   9.5385,   5.4472,   0.    ],
       [  0.    ,   5.4472,   5.1309,   6.3607],
       [  0.    ,   0.    ,   6.3607,   2.3306]])

In [142]:
linalg.hessenberg(Asimetrica).round(2)

array([[  1.  , -10.2 ,   0.  ,   0.  ],
       [-10.2 ,   9.54,   5.45,   0.  ],
       [  0.  ,   5.45,   5.13,   6.36],
       [  0.  ,   0.  ,   6.36,   2.33]])

In [102]:
def Diag_QR(A):
    l,c = A.shape
    Qfinal = np.eye((l))
    Q,R = np.linalg.qr(A)
    D = np.dot(R,Q)
    for i in range(c):
        Q,R = np.linalg.qr(D)
        A = np.dot(R,Q)
        Qfinal = np.dot(Qfinal,Q)
        D = np.copy(A)
    return D,Qfinal
    
    

In [106]:
MatDiag, QD = Diag_QR(MAT)

In [112]:
MatDiag.round(2)
l = MatDiag.shape[0]
for i in range(l):
    print(MatDiag[i,:].round(2))
    print("\n")

[ 47613.74     -0.        0.        0.  ]


[ -0.00000000e+00   1.66990000e+02  -1.00000000e-02   0.00000000e+00]


[  0.00000000e+00  -1.00000000e-02  -1.84100000e+01   0.00000000e+00]


[ 0.    0.    0.    0.97]




In [108]:
QD

array([[  2.28772562e-03,   9.50119130e-01,   2.97698773e-01,
          9.29722848e-02],
       [ -8.93860244e-01,  -1.37815572e-01,   4.11243260e-01,
          1.13576904e-01],
       [  4.48339857e-01,  -2.79611369e-01,   8.18414741e-01,
          2.25845448e-01],
       [  5.57276592e-05,  -9.89896963e-03,  -2.69168595e-01,
          9.63042198e-01]])

$$\Large\text{DIAGONALIZAÇÃO DE MATRIZES NÃO SIMÉTRICAS}$$
<hr/>
$$\Large\text{TRIDIAGONALIZAÇÃO NÃO É POSSÍVEL - RESULTADO: MATRIZ DE HESSENBERG}$$



In [139]:
#Matriz para os testes Iniciais
A = np.array([[12.0,-51.0,4],[6.0,167.0,-68.0],[-4.0,24.0,-41.0]]) #UUUQQQQQ
A

array([[  12.,  -51.,    4.],
       [   6.,  167.,  -68.],
       [  -4.,   24.,  -41.]])

In [140]:
Hen=TriD_HH(A)
Hen

array([[  12.    ,   -7.2111,   -0.    ],
       [  -7.2111,  123.3077,  -41.5385],
       [  -0.    , -133.5385,    2.6923]])

In [115]:
A

array([[  12.,  -51.,    4.],
       [   6.,  167.,  -68.],
       [  -4.,   24.,  -41.]])

In [117]:
linalg.hessenberg(A)

array([[  12.        ,   44.6533658 ,  -24.96150883],
       [  -7.21110255,  123.30769231,  -41.53846154],
       [   0.        , -133.53846154,    2.69230769]])

$$\Large\text{Autovetores e Autovalores por Decomposição QR (MÉTODO DE FRANCIS)}$$

In [2]:
#A deve ser simétrica
A =  np.array([[1.,  2.,  6.,  8.], 
[2.,  5.,  7.,  -3.],
[6.,  7.,  9.,  4.],
[8.,  -3., 4.,  3.]])
A

array([[ 1.,  2.,  6.,  8.],
       [ 2.,  5.,  7., -3.],
       [ 6.,  7.,  9.,  4.],
       [ 8., -3.,  4.,  3.]])

In [4]:
 np.linalg.eigvals(A)

array([ 18.32415517,   9.00237223,  -7.08096661,  -2.24556079])

In [14]:
np.linalg.eig(A)

(array([ 18.32415517,   9.00237223,  -7.08096661,  -2.24556079]),
 array([[ 0.45844793,  0.33576722,  0.69650628, -0.43813795],
        [ 0.36968635, -0.65711263, -0.29558961, -0.58665303],
        [ 0.72539798, -0.19471448,  0.03124555,  0.65947536],
        [ 0.35630782,  0.6461808 , -0.65309226, -0.17019285]]))

In [8]:
#PARA MATRIZES SIMÉTRICAS 
# A é uma matriz simétrica e qtd são as interações
def QR_AVeAv(A,qtd):
    l,c = A.shape
    Qfinal = np.eye((l))
    Q,R = np.linalg.qr(A)
    D = np.dot(R,Q)
    for i in range(qtd):
        Q,R = np.linalg.qr(D)
        A = np.dot(R,Q)
        Qfinal = np.dot(Qfinal,Q)
        D = np.copy(A)
    return D,Qfinal
        
    
    
    
    

In [9]:
Teste,QautVect = QR_AVeAv(A,100)
Teste.round(2)

array([[ 18.32,  -0.  ,   0.  ,  -0.  ],
       [  0.  ,   9.  ,   0.  ,  -0.  ],
       [ -0.  ,   0.  ,  -7.08,  -0.  ],
       [  0.  ,  -0.  ,   0.  ,  -2.25]])

In [11]:
QautVect

array([[ 0.81982155,  0.49390276, -0.25463475,  0.13825276],
       [-0.29498546,  0.7654933 ,  0.2579628 , -0.51035163],
       [ 0.48130784, -0.39545945,  0.42651451, -0.65577432],
       [ 0.09601543,  0.11701239,  0.82867467,  0.53887607]])

$$\large\text{OBSERVAÇÃO -  NORMA DE FROBENIUS }$$
$$\large{| A |_{F} = \sum_{i,j} abs[(a_{i,j})^{2}]^{1/2}  }$$

In [12]:
np.linalg.norm(Teste)

21.725560982400424

In [13]:
np.matrix.trace(Teste)

18.000000000000004

In [44]:
np.product([2,3,5])

30

In [39]:
(Teste[:0,1])+sum(Teste[0:,1])

9.0023722328259019

In [ ]:
import numpy as np
 
def QR_HH(A):
    m, n = A.shape
    Q = np.eye(m,n)
    for i in range(n - (m == n)): #preciso operacionar sobre as colunas da matriz "A"
        H = np.eye(m)
        H[i:, i:] = Householder(A[i:, i])
        print("matriz HouseHolder",H)
        Q = np.dot(Q, H)
        print("matriz Q",Q)
        A = np.dot(H, A)
        print("matriz A",A.round(2))
    return Q, A
 
def Householder(a):
    v = a / (a[0] + np.copysign(np.linalg.norm(a), a[0]))
    v[0] = 1
    H = np.eye(a.shape[0])
    H -= (2 / np.dot(v, v)) * np.dot(v[:, None], v[None, :])
    return H
 

In [34]:
def EhDiganoal(A):
    l,c = Teste.shape
    valor = 0
    for j in range(c):
        valor += (sum(A[:j,j]))(linalg.norm(A[j:,j]))) #tentar com somatório.
    if(valor<1e10-6):
        return True
    else:
        return False
        
         

In [35]:
EhDiganoal(Teste)

error: (offx>=0 && offx<len(x)) failed for 2nd keyword offx: dnrm2:offx=0

In [14]:
l,c = Teste.shape
for j in range(c):
    if()

4

In [13]:
Q_0,R_0 = np.linalg.qr(A)
R_0

array([[-10.24695077,  -2.92770022, -10.34454077,  -4.87950036],
       [  0.        ,  -8.85599071,  -7.64615591,  -0.64524522],
       [  0.        ,   0.        ,   4.06531376,   4.81885657],
       [  0.        ,   0.        ,   0.        ,  -7.11004614]])

In [14]:
Tr_0 = np.dot(Q_0.T,A)
Tr_0 = np.dot(Tr_0,R_0)


array([[ 105.  ,   55.93,   86.33,   36.73],
       [  -0.  ,   78.43,   36.63,  -26.54],
       [  -0.  ,   -0.  ,   16.53,  -14.67],
       [  -0.  ,   -0.  ,   -0.  ,   50.55]])

In [15]:
I = np.eye(3)
I

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [18]:
v = np.copy(I[0,:])
v -= I[1,:]
v

array([ 1., -1.,  0.])

In [48]:
y = y/LA.norm(y)
y

array([ 0.77849894,  0.62279916,  0.07784989])

In [39]:
q= v/ LA.norm(v)
q

array([ 0.57735027,  0.57735027,  0.57735027])

In [30]:
A
l,c = A.shape
v = np.random.rand(l,1)
q= v/ LA.norm(v)
y = np.dot(A,q)
Av = np.dot(q.T,y)
Av

array([[ 74.43916396]])

In [20]:
Autovalor, Autvetor = EvEv_mpot(A)

Autovetor [[ 156.13666968]]
vetor q [[-0.32814734]
 [ 0.93688136]
 [ 0.12071718]]
