$$\Large{ \textit{UNIVERSIDADE FEDERAL DO CEARÁ  } }$$

$$ \large{\textit{Departamento de Ciências da Computação }} $$


$$ \large{\textit{Mestrado e Doutorado em Ciências da Computação -  MDCC }} $$

<hr/>

$$\Large{{\textbf{ DISCIPLINA DE ÁLGEBRA LINEAR COMPUTACIONAL}}}$$



$$\large{\texttt{Docente: Professor Creto Vidal}}$$

$$\large{\texttt{Discente: Arnaldo Araújo}}$$
<hr/>

In [2]:
#realizando os imports para todo o projeto
import numpy as np
from scipy import linalg as LA ## testes
from __future__ import print_function 
from pprint import pprint
from math import sqrt
from scipy import random, linalg, dot, diag, all, allclose
from __future__ import print_function 
from pprint import pprint


$$\Large\text{TRIDIAGONALIZAÇÃO DE MATRIZES SIMÉTRICAS POR HOUSEHOLDER}$$

In [25]:
#A deve ser simétrica
Asimetrica =  np.array([[1.,  2.,  6.,  8.], 
[2.,  5.,  7.,  -3.],
[6.,  7.,  9.,  4.],
[8.,  -3., 4.,  3.]])
Asimetrica

array([[ 1.,  2.,  6.,  8.],
       [ 2.,  5.,  7., -3.],
       [ 6.,  7.,  9.,  4.],
       [ 8., -3.,  4.,  3.]])

In [26]:
A =  np.array([[1.,  5.,  2.,  8.], 
[2.,  5.,  5.,  -3.],
[1.,  7.,  9.,  4.],
[8.,  4., 12.,  3.]])
A

array([[  1.,   5.,   2.,   8.],
       [  2.,   5.,   5.,  -3.],
       [  1.,   7.,   9.,   4.],
       [  8.,   4.,  12.,   3.]])

In [7]:
def householder(x):
    x[0] = x[0] + np.sign(x[0]) * np.linalg.norm(x)
    x /= np.linalg.norm(x)
    return x

In [10]:
def tridiag_qr(T):
    R = T.copy()
    Qt = np.eye(T.shape[0])

    for i in range(T.shape[0] - 1):
        u = householder(T[i:i+2, i])

        R[i:i+2, :] = R[i:i+2, :] - 2 * np.outer(u, np.dot(u, R[i:i+2, :]))
        Qt[i:i+2, :] = Qt[i:i+2, :] - 2 * np.outer(u, np.dot(u, Qt[i:i+2, :]))

    return Qt.T, R

In [14]:
Auvect, Diago = tridiag_qr(Asimetrica)

In [16]:
Auvect.round(2)

array([[-0.99,  0.14, -0.02, -0.  ],
       [-0.14, -0.98,  0.12,  0.01],
       [ 0.  , -0.12, -0.99, -0.05],
       [ 0.  ,  0.  , -0.05,  1.  ]])

In [18]:
Diago.round(2)

array([[-1.  , -2.12, -6.91, -7.51],
       [-0.71, -0.72, -6.18,  3.57],
       [-6.37,  0.12, -0.27, -4.61],
       [ 7.68, -3.  ,  0.04,  2.76]])

In [37]:
linalg.hessenberg(Asimetrica).round(2)

array([[  1.  , -10.2 ,   0.  ,   0.  ],
       [-10.2 ,   9.54,   5.45,   0.  ],
       [  0.  ,   5.45,   5.13,   6.36],
       [  0.  ,   0.  ,   6.36,   2.33]])

In [74]:
def TridHH(A):
    Mat = np.copy(A)
    l,c = A.shape
    Hfinal = np.eye(l)
    for i in range(l-2):
        H = np.eye(l)
        V = Mat[i+1:,i]
        normaV = linalg.norm(V)
        N = np.copy(V)
        N[0] = N[0] + np.sign(N[0]) *normaV
        N /= np.linalg.norm(N)
        I = np.eye(N.shape[0])
        H[i+1:,i+1:] = I - 2*(np.outer(N,N.T))
        MT = np.dot(H,Mat)
        MT2 = np.dot(MT,H)
        Mat = np.copy(MT2)
        HT = np.dot(Hfinal,H)
        Hfinal = np.copy(HT)
    return Mat,Hfinal
        
        
        
        

In [76]:
Trid ,H = TridHH(Asimetrica)

In [78]:
M2.round(2)

array([[  1.  , -10.2 ,  -0.  ,  -0.  ],
       [-10.2 ,   9.54,   5.45,   0.  ],
       [ -0.  ,   5.45,   5.13,   6.36],
       [ -0.  ,   0.  ,   6.36,   2.33]])