$$\Large{ \textit{UNIVERSIDADE FEDERAL DO CEARÁ  } }$$

$$ \large{\textit{Departamento de Ciências da Computação }} $$


$$ \large{\textit{Mestrado e Doutorado em Ciências da Computação -  MDCC }} $$

<hr/>

$$\Large{{\textbf{ DISCIPLINA DE ÁLGEBRA LINEAR COMPUTACIONAL}}}$$



$$\large{\texttt{Docente: Professor Dr. Creto Vidal}}$$

$$\large{\texttt{Discente: Arnaldo Araújo}}$$
<hr/>


# Decomposição em Valores Singulares

**A decomposição em valores singulares de uma matriz $M$ é uma fatoração da forma $M=U \Sigma V^{*}$ onde:**
* $U$ é uma matriz unitária $mxm$. As $m$ colunas de $U$ são os vetores singulares à esquerda de $M$.

    * Os vetores singulares à esquerda de $M$ são os autovetores de $MM^{*}$

<hr/>

* $\Sigma$ é uma matriz diagonal $mxn$ com números reais não-negativos na diagonal. Tais valores $\Sigma_{i,i}$ são os chamados valores singulares de M.
    * Os valores singulares não-nulos de $M$ (ao longo da diagonal de $\Sigma$) são as raízes quadradas dos autovalores não-nulos de $ M^{*}M$  ou $ MM^{*}$ 

<hr/>



*  $V^{*}$(conjugada transposta de $V$) é uma matriz unitária $nxn$ As $n$ colunas de $V$ são os vetores singulares à direita de $M$.
    * Os vetores singulares à direita de $M$ são os autovetores de $M^{*}M$

<hr/>


$$\large{\text{OBS: Matriz Unitária } U \\ 
 U^{*}U=UU^{*}=I}\\\text{Sabendo que $U^{*}$ é a conjugada transposta, ou seja, $ U^{-1}=U^{*} $}$$

**PseudoCódigo - *DECOMPOSIÇÃO EM VALORES SINGULARES * **

*svd(A):*

> B ← $(A*A^{T})$

> e,v ← autovalores(B),autovetores(B)

> U ← v 

> C ← $(A^{T}*A)$

> e,v ← autovalores(C),autovetores(C)

> VT ← $v^{T}$ 
 


>para i=0, i<linhas(A), i++
>> faça
>>> $\Sigma_{i,i}$ ← $e_{i}$



> return U, $\Sigma$,VT

<hr/>


In [1]:
#realizando os imports para todo o projeto
import numpy as np
from scipy import linalg as LA ## testes
from __future__ import print_function 
from pprint import pprint
from math import sqrt
from scipy import random, linalg, dot, diag, all, allclose
from __future__ import print_function 
from pprint import pprint


<hr/>

$$\large\text{ OBSERVAÇÃO:Autovetores e Autovalores por Decomposição QR (MÉTODO DE FRANCIS)}$$

<hr/>


In [71]:
#METODO DE FRANCIS

def QR_AVeAv(A,qtd):
    l,c = A.shape
    Qfinal = np.eye((l))
    Q,R = np.linalg.qr(A)
    D = np.dot(R,Q)
    for i in range(qtd):
        Q,R = np.linalg.qr(D)
        A = np.dot(R,Q)
        Qfinal = np.dot(Qfinal,Q)
        D = np.copy(A)
    return D,Qfinal
        

<hr/>


$$\large{\text{Função para Ordenar os autovalores e os autovetores}}$$
<hr/>


In [36]:
#ordem crescente
def ordAA(val,vet):
    idx = (-val).argsort()[::-1]   
    val0 = val[idx]
    vet0 = vet[:,idx]
    return(val0,vet0)

<hr/>


In [37]:
A = np.array([[1, 1, 1, 0, 0],
              [3, 3, 3, 0, 0],
              [4, 4, 4, 0, 0],
              [5, 5, 5, 0, 0],
              [0, 2, 0, 4, 4],
              [0, 0, 0, 5, 5],
              [0, 1, 0, 2, 2]])
A

array([[1, 1, 1, 0, 0],
       [3, 3, 3, 0, 0],
       [4, 4, 4, 0, 0],
       [5, 5, 5, 0, 0],
       [0, 2, 0, 4, 4],
       [0, 0, 0, 5, 5],
       [0, 1, 0, 2, 2]])

In [38]:
#testes
A = np.array([[3.,1.,1.],[-1.,3.,1.]])
A

array([[ 3.,  1.,  1.],
       [-1.,  3.,  1.]])

In [58]:
A =np.array([[1.,2.],[3.,4.],[5.,6.],[7.,8.]])
A

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.]])

In [62]:
def svd(A):
    l,c = A.shape
    S = np.zeros((l,c))
    B = np.dot(A,A.T)
    C = np.dot(A.T,A)
    e,v = linalg.eig(B) #autovetores à esquerda
    e,v = ordAA(e,v)
    U = np.copy(v)
    #U = Ort_GS(MU) se u=tiver que ortogonalizar
    C = np.dot(A.T,A)
    e1,v1 = linalg.eig(C) #autovetores à direita
    e1,v1 = ordAA(e1,v1)
    V = np.copy(v1)
    if l<c:
        for i in range(e.shape[0]):
            S[i,i] = np.sqrt(e[i])
    else:
        for i in range(e1.shape[0]):
            S[i,i] = np.sqrt(e1[i])   
    return(U,S,V)

In [62]:
def svd(A):
    l,c = A.shape
    S = np.zeros((l,c))
    if l<c:
        B = np.dot(A,A.T)
        U = np.zeros((c,c))
        e,v = linalg.eig(B) #autovetores à esquerda
        for i in range(e.shape[0]):
             S[i,i] = np.sqrt(e[i])
        for k in range(U.shape[0]):
            
        
        


        
    
    
    
    
    S = np.zeros((l,c))
    C = np.dot(A.T,A)
    e,v = ordAA(e,v)
    U = np.copy(v)
    #U = Ort_GS(MU) se u=tiver que ortogonalizar
    C = np.dot(A.T,A)
    e1,v1 = linalg.eig(C) #autovetores à direita
    e1,v1 = ordAA(e1,v1)
    V = np.copy(v1)
    if l<c:
        
    else:
        for i in range(e1.shape[0]):
            S[i,i] = np.sqrt(e1[i])   
    return(U,S,V)

TESTES 1 -  linhas maiores que a colunas

In [68]:
A =np.array([[1.,2.],[3.,4.],[5.,6.],[7.,8.]])
A

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.]])

In [69]:
def svd(A):
    l,c = A.shape
    S = np.zeros((l,c))
    B = np.dot(A,A.T)
    C = np.dot(A.T,A)
    e,v = linalg.eig(B) #autovetores à esquerda
    e,v = ordAA(e,v)
    U = np.copy(v)
    #U = Ort_GS(MU) se u=tiver que ortogonalizar
    C = np.dot(A.T,A)
    e1,v1 = linalg.eig(C) #autovetores à direita
    e1,v1 = ordAA(e1,v1)
    V = np.copy(v1)
    if l<c:
        for i in range(e.shape[0]):
            S[i,i] = np.sqrt(e[i])
    else:
        for i in range(e1.shape[0]):
            S[i,i] = np.sqrt(e1[i])   
    return(U,S,V)

In [73]:
U1,S1,V1 = svd(A)

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:19: ComplexWarning: Casting complex values to real discards the imaginary part


In [74]:
S1

array([[  0.62682823,   0.        ],
       [  0.        ,  14.2690955 ],
       [  0.        ,   0.        ],
       [  0.        ,   0.        ]])

In [75]:
V1

array([[-0.7671874 , -0.64142303],
       [ 0.64142303, -0.7671874 ]])

In [76]:
U1

array([[ 0.41182088, -0.05811185,  0.82264747, -0.15248323],
       [-0.27993577, -0.32846157,  0.42137529, -0.34991837],
       [-0.67559109,  0.8312587 ,  0.0201031 , -0.54735351],
       [ 0.54370599, -0.44468528, -0.38116908, -0.74478865]])

In [78]:
np.dot(np.dot(U1,S1),V1.T)

array([[ 0.3338278 ,  0.80173211],
       [ 3.1408728 ,  3.48314026],
       [-7.283229  , -9.37147685],
       [ 3.8085284 ,  5.08660448]])

In [79]:
M1 = np.dot(A,V1)
M1

array([[  0.51565866,  -2.17579782],
       [  0.26412993,  -4.99301866],
       [  0.01260119,  -7.81023951],
       [ -0.23892754, -10.62746036]])

In [80]:
S1

array([[  0.62682823,   0.        ],
       [  0.        ,  14.2690955 ],
       [  0.        ,   0.        ],
       [  0.        ,   0.        ]])

In [82]:
M2 = np.zeros((M1.shape[0],M1.shape[1]))
for i in range(M1.shape[1]):
    M2[:,i] = M1[:,i]/S1[i,i]
M2

array([[ 0.82264747, -0.15248323],
       [ 0.42137529, -0.34991837],
       [ 0.0201031 , -0.54735351],
       [-0.38116908, -0.74478865]])

In [83]:
S1In = np.copy(S1)
for i in range(M1.shape[1]):
    S1In[i,i] = 

TypeError: ufunc 'invert' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [63]:
U0,S0,VT0 = svd(A)

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:19: ComplexWarning: Casting complex values to real discards the imaginary part


In [64]:
U0

array([[ 0.41182088, -0.05811185,  0.82264747, -0.15248323],
       [-0.27993577, -0.32846157,  0.42137529, -0.34991837],
       [-0.67559109,  0.8312587 ,  0.0201031 , -0.54735351],
       [ 0.54370599, -0.44468528, -0.38116908, -0.74478865]])

In [65]:
S0

array([[  0.62682823,   0.        ],
       [  0.        ,  14.2690955 ],
       [  0.        ,   0.        ],
       [  0.        ,   0.        ]])

In [65]:
S0

array([[  0.62682823,   0.        ],
       [  0.        ,  14.2690955 ],
       [  0.        ,   0.        ],
       [  0.        ,   0.        ]])

In [66]:
VT0

array([[-0.7671874 , -0.64142303],
       [ 0.64142303, -0.7671874 ]])

In [67]:
np.dot(np.dot(U0,S0),VT0.T)

array([[ 0.3338278 ,  0.80173211],
       [ 3.1408728 ,  3.48314026],
       [-7.283229  , -9.37147685],
       [ 3.8085284 ,  5.08660448]])

In [48]:
T2 = np.dot(T1,VT0)
T2

array([[-2.59913852,  0.27894853,  2.04124145],
       [-1.78264194,  1.9119417 , -2.04124145]])

In [29]:
l,c = A.shape
print(l,c)

2 3


In [30]:
if l > c:
    B = np.dot(A.T, A)
else:
    B = np.dot(A, A.T)
print(B)

[[ 11.   1.]
 [  1.  11.]]


In [31]:
e,v = np.linalg.eig(B)

In [32]:
e

array([ 12.,  10.])

In [55]:
linalg.norm(v[1])

0.9999999999999999

In [35]:
idx2 = (-e).argsort()[::-1]   
val0 = v[idx2]
vet0 = v[:,idx2]
vet0

array([[-0.70710678,  0.70710678],
       [ 0.70710678,  0.70710678]])

In [24]:
B.shape

(5, 5)

In [25]:
U = np.zeros((l,l))
U

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [28]:
V = np.zeros((c,c))
V

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [29]:
B[:,0]

array([51, 51, 51,  0,  0])

In [30]:
v[0]

array([ 0.56225841,  0.12664138, -0.70710678, -0.40966748, -0.03861644])

In [31]:
e[0]

155.77572778136977

In [32]:
e[0]*v[0]

array([  87.58621229,   19.72765342, -110.15007346,  -63.8162502 ,
         -6.0155036 ])

In [33]:
e[0]*v[0]/B[:,0]

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ 1.71737671,  0.38681673, -2.15980536,        -inf,        -inf])

In [36]:
V[0]=(e[0]*v[0])*(1/B[:,0])
V[0]

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ 1.71737671,  0.38681673, -2.15980536,        -inf,        -inf])

In [1]:
def Ort_GS(A):
    l,c = A.shape
    Q = np.zeros((l,c))
    x = A[:,0]
    e = x/(LA.norm(x))
    Q[:,0] = np.copy(e)
    for i in range(1,c):
        s = 0
        for k in range(i,0,-1):
            s = s + np.dot(np.dot(A[:,i],Q[:,k-1]),Q[:,k-1])
        x = A[:,i] - s
        e = x/(LA.norm(x))
        Q[:,i] = np.copy(e)
    return (Q)

In [46]:
%psource svd

In [ ]:
def svd(A):
    l,c = A.shape
    S = np.zeros((l,c))
    B = np.dot(A,A.T)
    e,v = linalg.eig(B)
    U = np.copy(v)
    #U = Ort_GS(MU) se u=tiver que ortogonalizar
    C = np.dot(A.T,A)
    e1,v1 = linalg.eig(C)
    VT = np.copy(v1.T)
    for i in range(e.shape[0]):
        S[i,i] = np.sqrt(e[i])
    return(U,S,VT)

In [5]:
print("--- FULL ---")
Uteste, steste, VTteste = np.linalg.svd(A, full_matrices=True)

print("U:\n {}".format(U))
print( "s:\n {}".format(s))
print ("VT:\n {}".format(VT))

--- FULL ---
U:
 [[ -1.37599126e-01  -2.36114514e-02  -1.08084718e-02   5.60112034e-01
   -3.75734575e-01  -7.00140042e-01  -1.87867287e-01]
 [ -4.12797378e-01  -7.08343543e-02  -3.24254153e-02   2.06393278e-01
    7.55974371e-01  -2.57991597e-01   3.77987186e-01]
 [ -5.50396503e-01  -9.44458057e-02  -4.32338870e-02  -7.24808963e-01
   -1.84603760e-01  -3.43988797e-01  -9.23018799e-02]
 [ -6.87995629e-01  -1.18057257e-01  -5.40423588e-02   3.43988797e-01
   -2.30754700e-01   5.70014004e-01  -1.15377350e-01]
 [ -1.52775087e-01   5.91100963e-01   6.53650843e-01   2.58497890e-16
    2.00000000e-01   0.00000000e+00  -4.00000000e-01]
 [ -7.22165140e-02   7.31311857e-01  -6.78209218e-01   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [ -7.63875433e-02   2.95550482e-01   3.26825421e-01   1.29248945e-16
   -4.00000000e-01   0.00000000e+00   8.00000000e-01]]
s:
 [  1.24810147e+01   9.50861406e+00   1.34555971e+00   3.04642685e-16
   0.00000000e+00]
VT:
 [[ -5.62258405e-0

In [6]:
print(U)

[[ -1.37599126e-01  -2.36114514e-02  -1.08084718e-02   5.60112034e-01
   -3.75734575e-01  -7.00140042e-01  -1.87867287e-01]
 [ -4.12797378e-01  -7.08343543e-02  -3.24254153e-02   2.06393278e-01
    7.55974371e-01  -2.57991597e-01   3.77987186e-01]
 [ -5.50396503e-01  -9.44458057e-02  -4.32338870e-02  -7.24808963e-01
   -1.84603760e-01  -3.43988797e-01  -9.23018799e-02]
 [ -6.87995629e-01  -1.18057257e-01  -5.40423588e-02   3.43988797e-01
   -2.30754700e-01   5.70014004e-01  -1.15377350e-01]
 [ -1.52775087e-01   5.91100963e-01   6.53650843e-01   2.58497890e-16
    2.00000000e-01   0.00000000e+00  -4.00000000e-01]
 [ -7.22165140e-02   7.31311857e-01  -6.78209218e-01   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [ -7.63875433e-02   2.95550482e-01   3.26825421e-01   1.29248945e-16
   -4.00000000e-01   0.00000000e+00   8.00000000e-01]]


In [7]:
print( "--- REDUCED ---")

Uteste, steste, VTteste = np.linalg.svd(A, full_matrices=False)

print( "U:\n {}".format(U))
print( "s:\n {}".format(s))
print( "VT:\n {}".format(VT))

--- REDUCED ---
U:
 [[ -1.37599126e-01  -2.36114514e-02  -1.08084718e-02   5.60112034e-01
   -3.75734575e-01]
 [ -4.12797378e-01  -7.08343543e-02  -3.24254153e-02   2.06393278e-01
    7.55974371e-01]
 [ -5.50396503e-01  -9.44458057e-02  -4.32338870e-02  -7.24808963e-01
   -1.84603760e-01]
 [ -6.87995629e-01  -1.18057257e-01  -5.40423588e-02   3.43988797e-01
   -2.30754700e-01]
 [ -1.52775087e-01   5.91100963e-01   6.53650843e-01   2.58497890e-16
    2.00000000e-01]
 [ -7.22165140e-02   7.31311857e-01  -6.78209218e-01   0.00000000e+00
    0.00000000e+00]
 [ -7.63875433e-02   2.95550482e-01   3.26825421e-01   1.29248945e-16
   -4.00000000e-01]]
s:
 [  1.24810147e+01   9.50861406e+00   1.34555971e+00   3.04642685e-16
   0.00000000e+00]
VT:
 [[ -5.62258405e-01  -5.92859901e-01  -5.62258405e-01  -9.01335372e-02
   -9.01335372e-02]
 [ -1.26641382e-01   2.87705846e-02  -1.26641382e-01   6.95376220e-01
    6.95376220e-01]
 [ -4.09667482e-01   8.04791520e-01  -4.09667482e-01  -9.12571001e-02
  

In [8]:
%psource np.linalg.svd


In [10]:
%psource np.linalg._umath_linalg.svd_m_f

No source found for np.linalg._umath_linalg.svd_m_f


In [3]:
def randomUnitVector(n):
    unnormalized = [normalvariate(0, 1) for _ in range(n)]
    theNorm = sqrt(sum(x * x for x in unnormalized))
    return [x / theNorm for x in unnormalized]

In [4]:
def svd_1d(A, epsilon=1e-10):
    ''' The one-dimensional SVD '''

    n, m = A.shape
    x = randomUnitVector(m)
    lastV = None
    currentV = x

    if n > m:
        B = np.dot(A.T, A)
    else:
        B = np.dot(A, A.T)

    iterations = 0
    while True:
        iterations += 1
        lastV = currentV
        currentV = np.dot(B, lastV)
        currentV = currentV / norm(currentV)

        if abs(np.dot(currentV, lastV)) > 1 - epsilon:
            print("converged in {} iterations!".format(iterations))
            return currentV


In [5]:


def svd(A, k=None, epsilon=1e-10):
    '''
        Compute the singular value decomposition of a matrix A
        using the power method. A is the input matrix, and k
        is the number of singular values you wish to compute.
        If k is None, this computes the full-rank decomposition.
    '''
    n, m = A.shape
    svdSoFar = []
    if k is None:
        k = min(n, m)

    for i in range(k):
        matrixFor1D = A.copy()

        for singularValue, u, v in svdSoFar[:i]:
            matrixFor1D -= singularValue * np.outer(u, v)

        v = svd_1d(matrixFor1D, epsilon=epsilon)  # next singular vector
        u_unnormalized = np.dot(A, v)
        sigma = norm(u_unnormalized)  # next singular value
        u = u_unnormalized / sigma

        svdSoFar.append((sigma, u, v))

    singularValues, us, vs = [np.array(x) for x in zip(*svdSoFar)]
    return singularValues, us.T, vs



In [6]:
#testes
A = np.array([[3.,1.,1.],[-1.,3.,1.]])
A

array([[ 3.,  1.,  1.],
       [-1.,  3.,  1.]])

In [7]:
svd(A)

NameError: name 'normalvariate' is not defined