$$\Large{ \textit{UNIVERSIDADE FEDERAL DO CEARÁ  } }$$

$$ \large{\textit{Departamento de Ciências da Computação }} $$


$$ \large{\textit{Mestrado e Doutorado em Ciências da Computação -  MDCC }} $$

<hr/>

$$\Large{{\textbf{ DISCIPLINA DE ÁLGEBRA LINEAR COMPUTACIONAL}}}$$



$$\large{\texttt{Docente: Professor Dr. Creto Vidal}}$$

$$\large{\texttt{Discente: Arnaldo Araújo}}$$
<hr/>


# Decomposição em Valores Singulares

**A decomposição em valores singulares de uma matriz $M$ é uma fatoração da forma $M=U \Sigma V^{*}$ onde:**
* $U$ é uma matriz unitária $mxm$. As $m$ colunas de $U$ são os vetores singulares à esquerda de $M$.

    * Os vetores singulares à esquerda de $M$ são os autovetores de $MM^{*}$

<hr/>

* $\Sigma$ é uma matriz diagonal $mxn$ com números reais não-negativos na diagonal. Tais valores $\Sigma_{i,i}$ são os chamados valores singulares de M.
    * Os valores singulares não-nulos de $M$ (ao longo da diagonal de $\Sigma$) são as raízes quadradas dos autovalores não-nulos de $ M^{*}M$  ou $ MM^{*}$ 

<hr/>



*  $V^{*}$(conjugada transposta de $V$) é uma matriz unitária $nxn$ As $n$ colunas de $V$ são os vetores singulares à direita de $M$.
    * Os vetores singulares à direita de $M$ são os autovetores de $M^{*}M$

<hr/>


$$\large{\text{OBS: Matriz Unitária } U \\ 
 U^{*}U=UU^{*}=I}\\\text{Sabendo que $U^{*}$ é a conjugada transposta, ou seja, $ U^{-1}=U^{*} $}$$

In [1]:
#realizando os imports para todo o projeto
import numpy as np
from scipy import linalg as LA ## testes
from __future__ import print_function 
from pprint import pprint
from math import sqrt
from scipy import random, linalg, dot, diag, all, allclose
from __future__ import print_function 
from pprint import pprint


In [3]:
A = np.array([[1, 1, 1, 0, 0],
              [3, 3, 3, 0, 0],
              [4, 4, 4, 0, 0],
              [5, 5, 5, 0, 0],
              [0, 2, 0, 4, 4],
              [0, 0, 0, 5, 5],
              [0, 1, 0, 2, 2]])
A

array([[1, 1, 1, 0, 0],
       [3, 3, 3, 0, 0],
       [4, 4, 4, 0, 0],
       [5, 5, 5, 0, 0],
       [0, 2, 0, 4, 4],
       [0, 0, 0, 5, 5],
       [0, 1, 0, 2, 2]])

In [11]:
Mata = np.dot(A.T,A)
Mata

array([[51, 51, 51,  0,  0],
       [51, 56, 51, 10, 10],
       [51, 51, 51,  0,  0],
       [ 0, 10,  0, 45, 45],
       [ 0, 10,  0, 45, 45]])

In [12]:
l,c = A.shape
print(l,c)

7 5


In [16]:
if l > c:
    B = np.dot(A.T, A)
else:
    B = np.dot(A, A.T)
print(B)

[[51 51 51  0  0]
 [51 56 51 10 10]
 [51 51 51  0  0]
 [ 0 10  0 45 45]
 [ 0 10  0 45 45]]


In [18]:
e,v = np.linalg.eig(B)

In [23]:
np.dot(e[0],v[0])

array([  87.58621229,   19.72765342, -110.15007346,  -63.8162502 ,
         -6.0155036 ])

In [24]:
B.shape

(5, 5)

In [25]:
U = np.zeros((l,l))
U

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [28]:
V = np.zeros((c,c))
V

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [29]:
B[:,0]

array([51, 51, 51,  0,  0])

In [30]:
v[0]

array([ 0.56225841,  0.12664138, -0.70710678, -0.40966748, -0.03861644])

In [31]:
e[0]

155.77572778136977

In [32]:
e[0]*v[0]

array([  87.58621229,   19.72765342, -110.15007346,  -63.8162502 ,
         -6.0155036 ])

In [33]:
e[0]*v[0]/B[:,0]

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ 1.71737671,  0.38681673, -2.15980536,        -inf,        -inf])

In [36]:
V[0]=(e[0]*v[0])*(1/B[:,0])
V[0]

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ 1.71737671,  0.38681673, -2.15980536,        -inf,        -inf])

In [5]:
print("--- FULL ---")
Uteste, steste, VTteste = np.linalg.svd(A, full_matrices=True)

print("U:\n {}".format(U))
print( "s:\n {}".format(s))
print ("VT:\n {}".format(VT))

--- FULL ---
U:
 [[ -1.37599126e-01  -2.36114514e-02  -1.08084718e-02   5.60112034e-01
   -3.75734575e-01  -7.00140042e-01  -1.87867287e-01]
 [ -4.12797378e-01  -7.08343543e-02  -3.24254153e-02   2.06393278e-01
    7.55974371e-01  -2.57991597e-01   3.77987186e-01]
 [ -5.50396503e-01  -9.44458057e-02  -4.32338870e-02  -7.24808963e-01
   -1.84603760e-01  -3.43988797e-01  -9.23018799e-02]
 [ -6.87995629e-01  -1.18057257e-01  -5.40423588e-02   3.43988797e-01
   -2.30754700e-01   5.70014004e-01  -1.15377350e-01]
 [ -1.52775087e-01   5.91100963e-01   6.53650843e-01   2.58497890e-16
    2.00000000e-01   0.00000000e+00  -4.00000000e-01]
 [ -7.22165140e-02   7.31311857e-01  -6.78209218e-01   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [ -7.63875433e-02   2.95550482e-01   3.26825421e-01   1.29248945e-16
   -4.00000000e-01   0.00000000e+00   8.00000000e-01]]
s:
 [  1.24810147e+01   9.50861406e+00   1.34555971e+00   3.04642685e-16
   0.00000000e+00]
VT:
 [[ -5.62258405e-0

In [6]:
print(U)

[[ -1.37599126e-01  -2.36114514e-02  -1.08084718e-02   5.60112034e-01
   -3.75734575e-01  -7.00140042e-01  -1.87867287e-01]
 [ -4.12797378e-01  -7.08343543e-02  -3.24254153e-02   2.06393278e-01
    7.55974371e-01  -2.57991597e-01   3.77987186e-01]
 [ -5.50396503e-01  -9.44458057e-02  -4.32338870e-02  -7.24808963e-01
   -1.84603760e-01  -3.43988797e-01  -9.23018799e-02]
 [ -6.87995629e-01  -1.18057257e-01  -5.40423588e-02   3.43988797e-01
   -2.30754700e-01   5.70014004e-01  -1.15377350e-01]
 [ -1.52775087e-01   5.91100963e-01   6.53650843e-01   2.58497890e-16
    2.00000000e-01   0.00000000e+00  -4.00000000e-01]
 [ -7.22165140e-02   7.31311857e-01  -6.78209218e-01   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [ -7.63875433e-02   2.95550482e-01   3.26825421e-01   1.29248945e-16
   -4.00000000e-01   0.00000000e+00   8.00000000e-01]]


In [7]:
print( "--- REDUCED ---")

Uteste, steste, VTteste = np.linalg.svd(A, full_matrices=False)

print( "U:\n {}".format(U))
print( "s:\n {}".format(s))
print( "VT:\n {}".format(VT))

--- REDUCED ---
U:
 [[ -1.37599126e-01  -2.36114514e-02  -1.08084718e-02   5.60112034e-01
   -3.75734575e-01]
 [ -4.12797378e-01  -7.08343543e-02  -3.24254153e-02   2.06393278e-01
    7.55974371e-01]
 [ -5.50396503e-01  -9.44458057e-02  -4.32338870e-02  -7.24808963e-01
   -1.84603760e-01]
 [ -6.87995629e-01  -1.18057257e-01  -5.40423588e-02   3.43988797e-01
   -2.30754700e-01]
 [ -1.52775087e-01   5.91100963e-01   6.53650843e-01   2.58497890e-16
    2.00000000e-01]
 [ -7.22165140e-02   7.31311857e-01  -6.78209218e-01   0.00000000e+00
    0.00000000e+00]
 [ -7.63875433e-02   2.95550482e-01   3.26825421e-01   1.29248945e-16
   -4.00000000e-01]]
s:
 [  1.24810147e+01   9.50861406e+00   1.34555971e+00   3.04642685e-16
   0.00000000e+00]
VT:
 [[ -5.62258405e-01  -5.92859901e-01  -5.62258405e-01  -9.01335372e-02
   -9.01335372e-02]
 [ -1.26641382e-01   2.87705846e-02  -1.26641382e-01   6.95376220e-01
    6.95376220e-01]
 [ -4.09667482e-01   8.04791520e-01  -4.09667482e-01  -9.12571001e-02
  

In [8]:
%psource np.linalg.svd


In [10]:
%psource np.linalg._umath_linalg.svd_m_f

No source found for np.linalg._umath_linalg.svd_m_f
