In [1]:
#realizando os imports para todo o projeto
import numpy as np
from scipy import linalg ## testes


In [3]:
A = np.array([[25, 15, -5], [15, 18,  0],[-5,  0, 11]])
A

array([[25, 15, -5],
       [15, 18,  0],
       [-5,  0, 11]])

In [13]:
TesteS = np.linalg.cholesky(A)
TesteS
TesteST = np.transpose(TesteS)
TesteST

array([[ 5.,  3., -1.],
       [ 0.,  3.,  1.],
       [ 0.,  0.,  3.]])

In [9]:
B = np.array([1,2,7])
B
BT = np.transpose(B)
BT

array([1, 2, 7])

## CHOSOLVE

In [6]:
def cho_solve(c_and_lower, b, overwrite_b=False, check_finite=True):
    """Solve the linear equations A x = b, given the Cholesky factorization of A.
    Parameters
    ----------
    (c, lower) : tuple, (array, bool)
        Cholesky factorization of a, as given by cho_factor
    b : array
        Right-hand side
    check_finite : boolean, optional
        Whether to check that the input matrices contain only finite numbers.
        Disabling may give a performance gain, but may result in problems
        (crashes, non-termination) if the inputs do contain infinities or NaNs.
    Returns
    -------
    x : array
        The solution to the system A x = b
    See also
    --------
    cho_factor : Cholesky factorization of a matrix
    """
    (c, lower) = c_and_lower
    if check_finite:
        b1 = asarray_chkfinite(b)
        c = asarray_chkfinite(c)
    else:
        b1 = asarray(b)
        c = asarray(c)
    if c.ndim != 2 or c.shape[0] != c.shape[1]:
        raise ValueError("The factored matrix c is not square.")
    if c.shape[1] != b1.shape[0]:
        raise ValueError("incompatible dimensions.")

    overwrite_b = overwrite_b or _datacopied(b1, b)

    potrs, = get_lapack_funcs(('potrs',), (c, b1))
    x, info = potrs(c, b1, lower=lower, overwrite_b=overwrite_b)
    if info != 0:
        raise ValueError('illegal value in %d-th argument of internal potrs'
                                                                    % -info)
    return x

In [16]:
TesteSOL = cho_solve((,B)

NameError: name 'lower' is not defined